# Croatian translation for apport
# Copyright (c) 2006 Rosetta Contributors and Canonical Ltd 2006
# This file is distributed under the same license as the apport package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2006.
#
msgid ""
msgstr ""
"Project-Id-Version: apport\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2012-06-15 07:52+0200\n"
"PO-Revision-Date: 2011-10-07 06:10+0000\n"
"Last-Translator: Dražen Odobašić <dodobas@geoinfo.geof.hr>\n"
"Language-Team: Croatian <hr@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2012-06-29 04:33+0000\n"
"X-Generator: Launchpad (build 15505)\n"
"Language: hr\n"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:103
#: ../apport/ui.py:103
msgid "This package does not seem to be installed correctly"
msgstr ""

#. TRANS: %s is the name of the operating system
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:106
#: ../apport/ui.py:106
#, python-format
msgid ""
"This is not an official %s package. Please remove any third party package "
"and try again."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:126
#: ../apport/ui.py:126
#, python-format
msgid ""
"You have some obsolete package versions installed. Please upgrade the "
"following packages and check if the problem still occurs:\n"
"\n"
"%s"
msgstr ""
"Imate instalirane neke zastarjele verzije paketa. Molim nadogradite sljedeće "
"pakete i provjerite pojavljuje li se problem ponovno:\n"
"\n"
"%s:"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:230
#: ../apport/ui.py:230
msgid "unknown program"
msgstr "nepoznati program"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:231
#: ../apport/ui.py:231
#, python-format
msgid "Sorry, the program \"%s\" closed unexpectedly"
msgstr "Žao nam je, \"%s\" je neplanirano prestao s radom"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:232
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1134
#: ../apport/ui.py:232 ../apport/ui.py:1134
#, python-format
msgid "Problem in %s"
msgstr "Problem u %s"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:233
#: ../apport/ui.py:233
msgid ""
"Your computer does not have enough free memory to automatically analyze the "
"problem and send a report to the developers."
msgstr ""
"Vaše računalo nema dovoljno slobodne memorije za automatsku analizu i slanje "
"izvještaja razvojnom timu."

#. package does not exist
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:247
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:254
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:260
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:298
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:306
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:378
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:381
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:579
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:948
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1088
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1092
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1111
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1117
#: ../apport/ui.py:247 ../apport/ui.py:254 ../apport/ui.py:260
#: ../apport/ui.py:298 ../apport/ui.py:306 ../apport/ui.py:378
#: ../apport/ui.py:381 ../apport/ui.py:579 ../apport/ui.py:948
#: ../apport/ui.py:1088 ../apport/ui.py:1092 ../apport/ui.py:1111
#: ../apport/ui.py:1117
#: ../debian/tmp/usr/share/apport/testsuite/test_ui.py:264
#: ../debian/tmp/usr/share/apport/testsuite/test_ui.py:281
#: ../debian/tmp/usr/share/apport/testsuite/test_ui.py:972
#: ../debian/tmp/usr/share/apport/testsuite/test_ui.py:992
#: ../debian/tmp/usr/share/apport/testsuite/test_ui.py:1003
#: ../debian/tmp/usr/share/apport/testsuite/test_ui.py:1014
msgid "Invalid problem report"
msgstr "Neispravan izvještaj o problemu"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:249
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1094
#: ../apport/ui.py:249 ../apport/ui.py:1094
msgid "This problem report is damaged and cannot be processed."
msgstr "Ovaj izvještaj o problemu je oštećen i ne može biti obrađen."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:255
#: ../apport/ui.py:255
msgid "The report belongs to a package that is not installed."
msgstr "Izvještaj pripada paketu koji nije instaliran."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:261
#: ../apport/ui.py:261
msgid "An error occurred while attempting to process this problem report:"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:299
#: ../apport/ui.py:299
msgid "You are not allowed to access this problem report."
msgstr "Niste ovlašteni za pristup ovom izvještaju o problemu."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:302
#: ../apport/ui.py:302
msgid "Error"
msgstr "Greška"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:303
#: ../apport/ui.py:303
msgid "There is not enough disk space available to process this report."
msgstr "Nema dovoljno prostora na disku za obradu ovog izvještaja."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:330
#: ../apport/ui.py:330
msgid "No package specified"
msgstr "Nema određenih paketa"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:331
#: ../apport/ui.py:331
msgid ""
"You need to specify a package or a PID. See --help for more information."
msgstr ""
"Morate odrediti paket ili PID. Pogledajte --help za više informacija."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:348
#: ../apport/ui.py:348
msgid "Invalid PID"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:349
#: ../apport/ui.py:349
msgid "The specified process ID does not belong to a program."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:357
#: ../apport/ui.py:357
msgid "Permission denied"
msgstr "Dozvola je uskraćena"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:358
#: ../apport/ui.py:358
msgid ""
"The specified process does not belong to you. Please run this program as the "
"process owner or as root."
msgstr ""
"Određeni proces vam ne pripada. Molimo pokrenite program kao vlasnik procesa "
"ili kao root."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:379
#: ../apport/ui.py:379
#, python-format
msgid "Symptom script %s did not determine an affected package"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:382
#: ../apport/ui.py:382
#, python-format
msgid "Package %s does not exist"
msgstr "Paket %s ne postoji"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:406
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:591
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:596
#: ../apport/ui.py:406 ../apport/ui.py:591 ../apport/ui.py:596
msgid "Cannot create report"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:421
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:467
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:484
#: ../apport/ui.py:421 ../apport/ui.py:467 ../apport/ui.py:484
msgid "Updating problem report"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:422
#: ../apport/ui.py:422
msgid ""
"You are not the reporter or subscriber of this problem report, or the report "
"is a duplicate or already closed.\n"
"\n"
"Please create a new report using \"apport-bug\"."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:431
#: ../apport/ui.py:431
msgid ""
"You are not the reporter of this problem report. It is much easier to mark a "
"bug as a duplicate of another than to move your comments and attachments to "
"a new bug.\n"
"\n"
"Subsequently, we recommend that you file a new bug report using \"apport-"
"bug\" and make a comment in this bug about the one you file.\n"
"\n"
"Do you really want to proceed?"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:468
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:485
#: ../apport/ui.py:468 ../apport/ui.py:485
msgid "No additional information collected."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:536
#: ../apport/ui.py:536
msgid "What kind of problem do you want to report?"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:553
#: ../apport/ui.py:553
msgid "Unknown symptom"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:554
#: ../apport/ui.py:554
#, python-format
msgid "The symptom \"%s\" is not known."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:582
#: ../apport/ui.py:582
msgid ""
"After closing this message please click on an application window to report a "
"problem about it."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:592
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:597
#: ../apport/ui.py:592 ../apport/ui.py:597
msgid "xprop failed to determine process ID of the window"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:611
#: ../apport/ui.py:611
msgid "%prog <report number>"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:613
#: ../apport/ui.py:613
msgid "Specify package name."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:615
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:664
#: ../apport/ui.py:615 ../apport/ui.py:664
msgid "Add an extra tag to the report. Can be specified multiple times."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:645
#: ../apport/ui.py:645
msgid ""
"%prog [options] [symptom|pid|package|program path|.apport/.crash file]"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:648
#: ../apport/ui.py:648
msgid ""
"Start in bug filing mode. Requires --package and an optional --pid, or just "
"a --pid. If neither is given, display a list of known symptoms. (Implied if "
"a single argument is given.)"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:650
#: ../apport/ui.py:650
msgid "Click a window as a target for filing a problem report."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:652
#: ../apport/ui.py:652
msgid "Start in bug updating mode. Can take an optional --package."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:654
#: ../apport/ui.py:654
msgid ""
"File a bug report about a symptom. (Implied if symptom name is given as only "
"argument.)"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:656
#: ../apport/ui.py:656
msgid ""
"Specify package name in --file-bug mode. This is optional if a --pid is "
"specified. (Implied if package name is given as only argument.)"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:658
#: ../apport/ui.py:658
msgid ""
"Specify a running program in --file-bug mode. If this is specified, the bug "
"report will contain more information.  (Implied if pid is given as only "
"argument.)"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:660
#: ../apport/ui.py:660
#, python-format
msgid ""
"Report the crash from given .apport or .crash file instead of the pending "
"ones in %s. (Implied if file is given as only argument.)"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:662
#: ../apport/ui.py:662
msgid ""
"In bug filing mode, save the collected information into a file instead of "
"reporting it. This file can then be reported later on from a different "
"machine."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:666
#: ../apport/ui.py:666
msgid "Print the Apport version number."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:800
#: ../apport/ui.py:800
msgid ""
"This will launch apport-retrace in a terminal window to examine the crash."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:801
#: ../apport/ui.py:801
msgid "Run gdb session"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:802
#: ../apport/ui.py:802
msgid "Run gdb session without downloading debug symbols"
msgstr ""

#. TRANSLATORS: %s contains the crash report file name
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:804
#: ../apport/ui.py:804
#, python-format
msgid "Update %s with fully symbolic stack trace"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:845
#: ../apport/ui.py:845
#, python-format
msgid ""
"The problem happened with the program %s which changed since the crash "
"occurred."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:949
#: ../apport/ui.py:949
msgid "Could not determine the package or source package name."
msgstr "Nije moguće odrediti paket ili ime izvornog paketa."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:967
#: ../apport/ui.py:967
msgid "Unable to start web browser"
msgstr "Nije moguće pokrenuti internet preglednik"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:968
#: ../apport/ui.py:968
#, python-format
msgid "Unable to start web browser to open %s."
msgstr "Nije moguće pokrenuti internet preglednik za otvaranje %s."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1043
#: ../apport/ui.py:1043
#, python-format
msgid "Please enter your account information for the %s bug tracking system"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1054
#: ../apport/ui.py:1054
msgid "Network problem"
msgstr "Problem s mrežom"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1056
#: ../apport/ui.py:1056
msgid ""
"Cannot connect to crash database, please check your Internet connection."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1083
#: ../apport/ui.py:1083
msgid "Memory exhaustion"
msgstr "Nedostatak memorije"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1084
#: ../apport/ui.py:1084
msgid "Your system does not have enough memory to process this crash report."
msgstr ""
"Vaš sustav nema dovoljno memorije za obradu ovog izvještaja o rušenju "
"sustava."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1107
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1116
#: ../apport/ui.py:1107 ../apport/ui.py:1116
msgid ""
"This problem report applies to a program which is not installed any more."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1137
#: ../apport/ui.py:1137
#, python-format
msgid ""
"The problem cannot be reported:\n"
"\n"
"%s"
msgstr ""
"Ovaj problem ne može biti prijavljen:\n"
"\n"
"%s"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1181
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1188
#: ../apport/ui.py:1181 ../apport/ui.py:1188
msgid "Problem already known"
msgstr "Problem je već poznat"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1182
#: ../apport/ui.py:1182
msgid ""
"This problem was already reported in the bug report displayed in the web "
"browser. Please check if you can add any further information that might be "
"helpful for the developers."
msgstr ""
"Ovaj problem je već prijavljen u izvještaju grešaka koji je prikazan u "
"internet pregledniku. Molim provjerite možete li dodati neke dodatne "
"informacije koje mogu pomoći razvojnom timu."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1189
#: ../apport/ui.py:1189
msgid "This problem was already reported to developers. Thank you!"
msgstr ""

#: ../bin/apport-retrace.py:39 ../debian/tmp/usr/bin/apport-retrace.py:39
msgid "%prog [options] <apport problem report | crash ID>"
msgstr ""

#: ../bin/apport-retrace.py:41 ../debian/tmp/usr/bin/apport-retrace.py:41
msgid "Do not put the new traces into the report, but write them to stdout."
msgstr ""

#: ../bin/apport-retrace.py:43 ../debian/tmp/usr/bin/apport-retrace.py:43
msgid ""
"Start an interactive gdb session with the report's core dump (-o ignored; "
"does not rewrite report)"
msgstr ""

#: ../bin/apport-retrace.py:45 ../debian/tmp/usr/bin/apport-retrace.py:45
msgid ""
"Write modified report to given file instead of changing the original report"
msgstr ""

#: ../bin/apport-retrace.py:47 ../debian/tmp/usr/bin/apport-retrace.py:47
msgid "Remove the core dump from the report after stack trace regeneration"
msgstr ""

#: ../bin/apport-retrace.py:49 ../debian/tmp/usr/bin/apport-retrace.py:49
msgid "Override report's CoreFile"
msgstr ""

#: ../bin/apport-retrace.py:51 ../debian/tmp/usr/bin/apport-retrace.py:51
msgid "Override report's ExecutablePath"
msgstr ""

#: ../bin/apport-retrace.py:53 ../debian/tmp/usr/bin/apport-retrace.py:53
msgid "Override report's ProcMaps"
msgstr ""

#: ../bin/apport-retrace.py:55 ../debian/tmp/usr/bin/apport-retrace.py:55
msgid "Rebuild report's Package information"
msgstr ""

#: ../bin/apport-retrace.py:57 ../debian/tmp/usr/bin/apport-retrace.py:57
msgid ""
"Build a temporary sandbox and download/install the necessary packages and "
"debug symbols in there; without this option it assumes that the necessary "
"packages and debug symbols are already installed in the system. The argument "
"points to the packaging system configuration base directory; if you specify "
"\"system\", it will use the system configuration files, but will then only "
"be able to retrace crashes that happened on the currently running release."
msgstr ""

#: ../bin/apport-retrace.py:59 ../debian/tmp/usr/bin/apport-retrace.py:59
msgid ""
"Report download/install progress when installing packages into sandbox"
msgstr ""

#: ../bin/apport-retrace.py:61 ../debian/tmp/usr/bin/apport-retrace.py:61
msgid "Prepend timestamps to log messages, for batch operation"
msgstr ""

#: ../bin/apport-retrace.py:63 ../debian/tmp/usr/bin/apport-retrace.py:63
msgid "Cache directory for packages downloaded in the sandbox"
msgstr ""

#: ../bin/apport-retrace.py:65 ../debian/tmp/usr/bin/apport-retrace.py:65
msgid ""
"Directory for unpacked packages. Future runs will assume that any already "
"downloaded package is also extracted to this sandbox."
msgstr ""

#: ../bin/apport-retrace.py:67 ../debian/tmp/usr/bin/apport-retrace.py:67
msgid ""
"Install an extra package into the sandbox (can be specified multiple times)"
msgstr ""

#: ../bin/apport-retrace.py:69 ../debian/tmp/usr/bin/apport-retrace.py:69
msgid ""
"Path to a file with the crash database authentication information. This is "
"used when specifying a crash ID to upload the retraced stack traces (only if "
"neither -g, -o, nor -s are specified)"
msgstr ""

#: ../bin/apport-retrace.py:71 ../debian/tmp/usr/bin/apport-retrace.py:71
msgid ""
"Display retraced stack traces and ask for confirmation before sending them "
"to the crash database."
msgstr ""

#: ../bin/apport-retrace.py:73 ../debian/tmp/usr/bin/apport-retrace.py:73
msgid ""
"Path to the duplicate sqlite database (default: no duplicate checking)"
msgstr ""

#: ../bin/apport-retrace.py:78 ../debian/tmp/usr/bin/apport-retrace.py:78
msgid "incorrect number of arguments; use --help for a short help"
msgstr ""

#: ../bin/apport-retrace.py:82 ../debian/tmp/usr/bin/apport-retrace.py:82
msgid ""
"you either need to do a local operation (-s, -g, -o) or supply an "
"authentication file (--auth); see --help for a short help"
msgstr ""

#. translators: don't translate y/n, apport currently only checks for "y"
#: ../bin/apport-retrace.py:116 ../debian/tmp/usr/bin/apport-retrace.py:116
msgid "OK to send these as attachments? [y/n]"
msgstr ""

#: ../gtk/apport-gtk-mime.desktop.in.h:1 ../kde/apport-kde-mime.desktop.in.h:1
#: ../kde/apport-kde.desktop.in.h:1 ../gtk/apport-gtk.desktop.in.h:1
msgid "Report a problem..."
msgstr "Prijavite problem..."

#: ../gtk/apport-gtk-mime.desktop.in.h:2 ../kde/apport-kde-mime.desktop.in.h:2
#: ../kde/apport-kde.desktop.in.h:2 ../gtk/apport-gtk.desktop.in.h:2
msgid "Report a malfunction to the developers"
msgstr "Prijavite kvar razvojnom timu"

#: ../debian/tmp/usr/bin/apport-unpack.py:22 ../bin/apport-unpack.py:22
#, python-format
msgid "Usage: %s <report> <target directory>"
msgstr ""

#: ../debian/tmp/usr/bin/apport-unpack.py:46 ../bin/apport-unpack.py:46
msgid "Destination directory exists and is not empty."
msgstr ""

#: ../debian/tmp/usr/share/apport/kernel_oops.py:28 ../data/kernel_oops.py:28
msgid "Your system might become unstable now and might need to be restarted."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:162
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:360
#: ../gtk/apport-gtk.py:165
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:278
#: ../bin/apport-cli.py:175 ../debian/tmp/usr/share/apport/apport-gtk.py:165
#: ../kde/apport-kde.py:162 ../debian/tmp/usr/bin/apport-cli.py:175
msgid "Send problem report to the developers?"
msgstr "Pošaljite izvještaj o problemu razvojnom timu?"

#: ../debian/tmp/usr/share/apport/apport-kde.py:170
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:368
#: ../gtk/apport-gtk.py:174
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:284
#: ../debian/tmp/usr/share/apport/apport-gtk.py:174 ../kde/apport-kde.py:170
msgid "Send"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:176
#: ../debian/tmp/usr/share/apport/apport-kde.py:209
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:109
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:255
#: ../gtk/apport-gtk.py:153
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:107
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:245
#: ../debian/tmp/usr/share/apport/apport-gtk.py:153 ../kde/apport-kde.py:176
#: ../kde/apport-kde.py:209
#, python-format
msgid "Sorry, %s has experienced an internal error."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:184 ../gtk/apport-gtk.py:211
#: ../debian/tmp/usr/share/apport/apport-gtk.py:211 ../kde/apport-kde.py:184
#, python-format
msgid "Package: %s"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:190
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:139
#: ../gtk/apport-gtk.py:218
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:134
#: ../debian/tmp/usr/share/apport/apport-gtk.py:218 ../kde/apport-kde.py:190
msgid "Sorry, a problem occurred while installing software."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:196 ../gtk/apport-gtk.py:227
#: ../debian/tmp/usr/share/apport/apport-gtk.py:227 ../kde/apport-kde.py:196
#, python-format
msgid "The application %s has closed unexpectedly."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:202 ../gtk/apport-gtk.ui.h:9
#: ../gtk/apport-gtk.py:232 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:9
#: ../debian/tmp/usr/share/apport/apport-gtk.py:232 ../kde/apport-kde.py:202
msgid "Leave Closed"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:203
#: ../debian/tmp/usr/share/apport/apport-kde.py:340
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:227
#: ../gtk/apport-gtk.py:233
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:216
#: ../debian/tmp/usr/share/apport/apport-gtk.py:233 ../kde/apport-kde.py:203
#: ../kde/apport-kde.py:340
msgid "Relaunch"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:206
#: ../debian/tmp/usr/share/apport/apport-kde.py:215
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:116
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:146
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:186
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:265
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:306
#: ../gtk/apport-gtk.ui.h:10 ../gtk/apport-gtk.py:195 ../gtk/apport-gtk.py:236
#: ../gtk/apport-gtk.py:247 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:10
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:112
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:139
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:176
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:253
#: ../debian/tmp/usr/share/apport/apport-gtk.py:195
#: ../debian/tmp/usr/share/apport/apport-gtk.py:236
#: ../debian/tmp/usr/share/apport/apport-gtk.py:247 ../kde/apport-kde.py:206
#: ../kde/apport-kde.py:215
msgid "Continue"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:212
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:257
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:298
#: ../gtk/apport-gtk.ui.h:4 ../gtk/apport-gtk.py:244
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:4
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:247
#: ../debian/tmp/usr/share/apport/apport-gtk.py:244 ../kde/apport-kde.py:212
msgid "If you notice further problems, try restarting the computer."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:216 ../gtk/apport-gtk.py:248
#: ../debian/tmp/usr/share/apport/apport-gtk.py:248 ../kde/apport-kde.py:216
msgid "Ignore future problems of this type"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:251 ../gtk/apport-gtk.py:512
#: ../debian/tmp/usr/share/apport/apport-gtk.py:512 ../kde/apport-kde.py:251
msgid "Hide Details"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:254 ../gtk/apport-gtk.ui.h:7
#: ../gtk/apport-gtk.py:183 ../gtk/apport-gtk.py:508
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:7
#: ../debian/tmp/usr/share/apport/apport-gtk.py:183
#: ../debian/tmp/usr/share/apport/apport-gtk.py:508 ../kde/apport-kde.py:254
msgid "Show Details"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:277 ../kde/apport-kde.py:277
msgid "Username:"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:278 ../kde/apport-kde.py:278
msgid "Password:"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:321 ../gtk/apport-gtk.py:129
#: ../bin/apport-cli.py:146 ../debian/tmp/usr/share/apport/apport-gtk.py:129
#: ../kde/apport-kde.py:321 ../debian/tmp/usr/bin/apport-cli.py:146
msgid "(binary data)"
msgstr "(binarni podatci)"

#: ../debian/tmp/usr/share/apport/apport-kde.py:365 ../kde/apport-kde.py:365
msgid "Collecting Problem Information"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:366 ../bin/apport-cli.py:235
#: ../kde/apport-kde.py:366 ../debian/tmp/usr/bin/apport-cli.py:235
msgid "Collecting problem information"
msgstr "Skupljanje informacija o problemu"

#: ../debian/tmp/usr/share/apport/apport-kde.py:367 ../kde/apport-kde.py:367
msgid ""
"The collected information can be sent to the developers to improve the "
"application. This might take a few minutes."
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:393 ../kde/apport-kde.py:393
msgid "Uploading Problem Information"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-kde.py:394 ../gtk/apport-gtk.ui.h:13
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:13 ../bin/apport-cli.py:248
#: ../kde/apport-kde.py:394 ../debian/tmp/usr/bin/apport-cli.py:248
msgid "Uploading problem information"
msgstr "Slanje informacija o problemu"

#: ../debian/tmp/usr/share/apport/apport-kde.py:395 ../gtk/apport-gtk.ui.h:15
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:15 ../kde/apport-kde.py:395
msgid ""
"The collected information is being sent to the bug tracking system. This "
"might take a few minutes."
msgstr ""
"Prikupljene informacije se šalju sustavu za praćenje grešaka. Ovo može "
"potrajati nekoliko minuta."

#: ../debian/tmp/usr/share/apport/apport-kde.py:429
#: ../debian/tmp/usr/share/apport/apport-kde.py:465 ../gtk/apport-gtk.ui.h:1
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:1 ../kde/apport-kde.py:429
#: ../kde/apport-kde.py:465
msgid "Apport"
msgstr ""

#: ../bin/apport-cli.py:73 ../debian/tmp/usr/bin/apport-cli.py:73
msgid "Press any key to continue..."
msgstr "Pritisnite bilo koju tipku za nastavak..."

#: ../bin/apport-cli.py:80 ../debian/tmp/usr/bin/apport-cli.py:80
msgid "What would you like to do? Your options are:"
msgstr "Što želite napraviti? Vaše mogućnosti su:"

#: ../bin/apport-cli.py:84 ../debian/tmp/usr/bin/apport-cli.py:84
#, python-format
msgid "Please choose (%s):"
msgstr "Molim odaberite (%s):"

#: ../bin/apport-cli.py:144 ../debian/tmp/usr/bin/apport-cli.py:144
#, python-format
msgid "(%i bytes)"
msgstr ""

#: ../bin/apport-cli.py:176 ../debian/tmp/usr/bin/apport-cli.py:176
msgid ""
"After the problem report has been sent, please fill out the form in the\n"
"automatically opened web browser."
msgstr ""
"Nakon slanja izvještaja o problemu, molimo ispunite formular u\n"
"automatski otvorenom internet pregledniku."

#: ../bin/apport-cli.py:179 ../debian/tmp/usr/bin/apport-cli.py:179
#, python-format
msgid "&Send report (%s)"
msgstr "&Pošaljite izvještaj (%s)"

#: ../bin/apport-cli.py:183 ../debian/tmp/usr/bin/apport-cli.py:183
msgid "&Examine locally"
msgstr ""

#: ../bin/apport-cli.py:187 ../debian/tmp/usr/bin/apport-cli.py:187
msgid "&View report"
msgstr "&Pogledajte izvještaj"

#: ../bin/apport-cli.py:188 ../debian/tmp/usr/bin/apport-cli.py:188
msgid "&Keep report file for sending later or copying to somewhere else"
msgstr ""
"&Zadržite dokument izvještaja za kasnije slanje ili kopiranje na neko drugo "
"mjesto"

#: ../bin/apport-cli.py:189 ../debian/tmp/usr/bin/apport-cli.py:189
msgid "Cancel and &ignore future crashes of this program version"
msgstr "Poništi i &ignoriraj buduća rušenja ove verzije programa"

#: ../bin/apport-cli.py:191 ../bin/apport-cli.py:268 ../bin/apport-cli.py:300
#: ../bin/apport-cli.py:321 ../debian/tmp/usr/bin/apport-cli.py:191
#: ../debian/tmp/usr/bin/apport-cli.py:268
#: ../debian/tmp/usr/bin/apport-cli.py:300
#: ../debian/tmp/usr/bin/apport-cli.py:321
msgid "&Cancel"
msgstr "&Odustani"

#: ../bin/apport-cli.py:219 ../debian/tmp/usr/bin/apport-cli.py:219
msgid "Problem report file:"
msgstr "Dokument izvještaja o problemu:"

#: ../bin/apport-cli.py:225 ../bin/apport-cli.py:230
#: ../debian/tmp/usr/bin/apport-cli.py:225
#: ../debian/tmp/usr/bin/apport-cli.py:230
msgid "&Confirm"
msgstr "&Potvrdi"

#: ../bin/apport-cli.py:229 ../debian/tmp/usr/bin/apport-cli.py:229
#, python-format
msgid "Error: %s"
msgstr "Greška: %s"

#: ../bin/apport-cli.py:236 ../debian/tmp/usr/bin/apport-cli.py:236
msgid ""
"The collected information can be sent to the developers to improve the\n"
"application. This might take a few minutes."
msgstr ""
"Prikupljene informacije mogu biti poslane razvojnom timu kako bi se "
"aplikacija\n"
"poboljšala. To može potrajati nekoliko minuta."

#: ../bin/apport-cli.py:249 ../debian/tmp/usr/bin/apport-cli.py:249
msgid ""
"The collected information is being sent to the bug tracking system.\n"
"This might take a few minutes."
msgstr ""
"Prikupljene informacije se šalju sustavu za praćenje grešaka.\n"
"Ovo može potrajati nekoliko minuta."

#: ../bin/apport-cli.py:299 ../debian/tmp/usr/bin/apport-cli.py:299
msgid "&Done"
msgstr ""

#: ../bin/apport-cli.py:305 ../debian/tmp/usr/bin/apport-cli.py:305
msgid "none"
msgstr ""

#: ../bin/apport-cli.py:306 ../debian/tmp/usr/bin/apport-cli.py:306
#, python-format
msgid "Selected: %s. Multiple choices:"
msgstr ""

#: ../bin/apport-cli.py:322 ../debian/tmp/usr/bin/apport-cli.py:322
msgid "Choices:"
msgstr ""

#: ../bin/apport-cli.py:336 ../debian/tmp/usr/bin/apport-cli.py:336
msgid "Path to file (Enter to cancel):"
msgstr ""

#: ../bin/apport-cli.py:342 ../debian/tmp/usr/bin/apport-cli.py:342
msgid "File does not exist."
msgstr ""

#: ../bin/apport-cli.py:344 ../debian/tmp/usr/bin/apport-cli.py:344
msgid "This is a directory."
msgstr ""

#: ../bin/apport-cli.py:350 ../debian/tmp/usr/bin/apport-cli.py:350
msgid "To continue, you must visit the following URL:"
msgstr ""

#: ../bin/apport-cli.py:352 ../debian/tmp/usr/bin/apport-cli.py:352
msgid ""
"You can launch a browser now, or copy this URL into a browser on another "
"computer."
msgstr ""

#: ../bin/apport-cli.py:354 ../debian/tmp/usr/bin/apport-cli.py:354
msgid "Launch a browser now"
msgstr ""

#: ../bin/apport-cli.py:368 ../debian/tmp/usr/bin/apport-cli.py:368
msgid "No pending crash reports. Try --help for more information."
msgstr ""
"Nema neposlanih izvještaja o rušenju. Pokušajte --help za više informacija."

#: ../debian/tmp/usr/share/apport/apportcheckresume.py:67
#: ../data/apportcheckresume.py:67
msgid ""
"This occured during a previous suspend and prevented it from resuming "
"properly."
msgstr ""

#: ../debian/tmp/usr/share/apport/apportcheckresume.py:69
#: ../data/apportcheckresume.py:69
msgid ""
"This occured during a previous hibernate and prevented it from resuming "
"properly."
msgstr ""

#: ../debian/tmp/usr/share/apport/apportcheckresume.py:74
#: ../data/apportcheckresume.py:74
msgid ""
"The resume processing hung very near the end and will have appeared to have "
"completed normally."
msgstr ""

#: ../gtk/apport-gtk.ui.h:2 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:2
msgid "Crash report"
msgstr ""

#: ../gtk/apport-gtk.ui.h:3 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:3
msgid "<big><b>Sorry, an internal error happened.</b></big>"
msgstr ""

#: ../gtk/apport-gtk.ui.h:5 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:5
msgid "Send an error report to help fix this problem"
msgstr ""

#: ../gtk/apport-gtk.ui.h:6 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:6
msgid "Ignore future problems of this program version"
msgstr ""

#: ../gtk/apport-gtk.ui.h:8 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:8
msgid "_Examine locally"
msgstr ""

#: ../gtk/apport-gtk.ui.h:11 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:11
msgid "<big><b>Collecting problem information</b></big>"
msgstr "<big><b>Sakupljanje podataka o problemu</b></big>"

#: ../gtk/apport-gtk.ui.h:12 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:12
msgid ""
"Information is being collected that may help the developers fix the problem "
"you report."
msgstr ""
"Skupljaju se informacije koje mogu pomoći razvojnom timu pri rješavanju "
"problema koje prijavljujete."

#: ../gtk/apport-gtk.ui.h:14 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:14
msgid "<big><b>Uploading problem information</b></big>"
msgstr "<big><b>Učitavanje informacija o problemu</b></big>"

#: ../gtk/apport-gtk.py:144 ../debian/tmp/usr/share/apport/apport-gtk.py:144
#, python-format
msgid "Sorry, the application %s has closed unexpectedly."
msgstr ""

#: ../gtk/apport-gtk.py:147 ../debian/tmp/usr/share/apport/apport-gtk.py:147
#, python-format
msgid "Sorry, %s has closed unexpectedly."
msgstr ""

#: ../kde/apport-kde-mimelnk.desktop.in.h:1
msgid "Apport crash file"
msgstr ""

#~ msgid "You can help the developers to fix the problem by reporting it."
#~ msgstr "Možete pomoći razvojnom timu da riješi problem prijavom istog."

#, python-format
#~ msgid "The package \"%s\" failed to install or upgrade."
#~ msgstr "Paket \"%s\" se nije uspio instalirati ili nadograditi"

#, no-c-format, python-format
#~ msgid "Complete report (recommended; %s)"
#~ msgstr "Potpun izvještaj (preporučeno; %s)"

#~ msgid ""
#~ "<big><b>Send problem report to the developers?</b></big>\n"
#~ "\n"
#~ "After the problem report has been sent, please fill out the form in the "
#~ "automatically opened web browser."
#~ msgstr ""
#~ "<big><b>Poslati izvještaj o problemu razvojnom timu?</b></big>\n"
#~ "\n"
#~ "Nakon što je izvještaj o problemu poslan, molim ispunite formular u "
#~ "automatski otvorenom internet pregledniku."

#~ msgid ""
#~ "If you were not doing anything confidential (entering passwords or other "
#~ "private information), you can help to improve the application by reporting "
#~ "the problem."
#~ msgstr ""
#~ "Ako niste radili nešto povjerljivo (unosili lozinke ili nešto slično), "
#~ "možete pomoći u poboljšanju aplikacije prijavljivanjem problema razvojnom "
#~ "timu."

#~ msgid "Application problem"
#~ msgstr "Problem s aplikacijom"

#~ msgid "_Send Report"
#~ msgstr "_Pošalji izvješće"

#~ msgid ""
#~ "If you were not doing anything confidential (entering passwords or other\n"
#~ "private information), you can help to improve the application by reporting\n"
#~ "the problem."
#~ msgstr ""
#~ "Ako niste radili ništa povjerljivo (unosili lozinke ili druge\n"
#~ "privatne informacije), možete pomoći unaprijediti aplikaciju prijavom\n"
#~ "problema."

#, python-format
#~ msgid "%s closed unexpectedly on %s at %s."
#~ msgstr "%s neočekivano prekinut na %s u %s."

#~ msgid "Restart _Program"
#~ msgstr "Ponovo pokreni _Program"

#, no-c-format
#~ msgid ""
#~ "<span weight=\"bold\" size=\"larger\">Sorry, the package \"%s\" failed to "
#~ "install or upgrade.</span>"
#~ msgstr ""
#~ "<span weight=\"bold\" size=\"larger\">Nažalost, paket \"%s\" se nije uspio "
#~ "instalirati ili nadograditi</span>"

#, python-format
#~ msgid "&Send complete report (recommended; %s)"
#~ msgstr "&Pošaljite potpun izvještaj (preporučeno; %s)"

#, no-c-format, python-format
#~ msgid "Reduced report (slow Internet connection; %s)"
#~ msgstr "Sažeti izvještaj (spora Internet veza; %s)"

#~ msgid "_Ignore future crashes of this program version"
#~ msgstr "_Zanemari buduća rušenja ove verzije programa"

#, python-format
#~ msgid "Send &reduced report (slow Internet connection; %s)"
#~ msgstr "Pošaljite &sažeti izvještaj (spora Internet veza; %s)"

#~ msgid ""
#~ "This will remove some large items from the report. These are very useful for "
#~ "developers to debug the problem, but might be too big for you to upload if "
#~ "you have a slow internet connection."
#~ msgstr ""
#~ "Ovo će odstraniti neke veće dijelove izvještaja. Oni su vrlo korisni "
#~ "razvojnom timu za otklanjanje problema, ali mogu biti preveliki za slanje "
#~ "ako imate sporu vezu s internetom."

#~ msgid "&Report Problem..."
#~ msgstr "&Prijavi Problem..."

#~ msgid "_Report Problem..."
#~ msgstr "_Prijavi problem..."

#~ msgid "Kernel problem"
#~ msgstr "Problem s kernelom"

#~ msgid ""
#~ "You can help the developers to fix the package by reporting the problem."
#~ msgstr ""
#~ "I vi možete pomoći razvojnom timu da popravi paket prijavom problema."

#, python-format
#~ msgid "This is not a genuine %s package"
#~ msgstr "Ovo nije izvorni %s paket"

#~ msgid "Content of the report"
#~ msgstr "Sadržaj izvještaja"

#~ msgid "Package problem"
#~ msgstr "Problem s paketom"
