# Icelandic translation for apport
# Copyright (c) 2008 Rosetta Contributors and Canonical Ltd 2008
# This file is distributed under the same license as the apport package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2008.
#
msgid ""
msgstr ""
"Project-Id-Version: apport\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2015-09-10 11:16+0200\n"
"PO-Revision-Date: 2015-04-27 21:46+0000\n"
"Last-Translator: Páll Haraldsson <Pall.Haraldsson@gmail.com>\n"
"Language-Team: Icelandic <is@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2018-05-17 05:15+0000\n"
"X-Generator: Launchpad (build 18658)\n"
"Language: is\n"

#: ../kde/apport-kde.py:457 ../kde/apport-kde.py:493
#: ../debian/tmp/usr/share/apport/apport-kde.py:457
#: ../debian/tmp/usr/share/apport/apport-kde.py:493
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:1 ../gtk/apport-gtk.ui.h:1
msgid "Apport"
msgstr "Apport"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:2 ../gtk/apport-gtk.ui.h:2
msgid "Cancel"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:3 ../gtk/apport-gtk.ui.h:3
msgid "OK"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:2 ../gtk/apport-gtk.ui.h:2
msgid "Crash report"
msgstr "Hrunskýrsla"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:3 ../gtk/apport-gtk.ui.h:3
msgid "<big><b>Sorry, an internal error happened.</b></big>"
msgstr "<big><b>Því miður, upp kom innri villa.</b></big>"

#: ../kde/apport-kde.py:227
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:339
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:379
#: ../gtk/apport-gtk.py:300 ../debian/tmp/usr/share/apport/apport-kde.py:227
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:4
#: ../debian/tmp/usr/share/apport/apport-gtk.py:300 ../gtk/apport-gtk.ui.h:4
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:292
msgid "If you notice further problems, try restarting the computer."
msgstr ""
"Ef þú verður var við fleiri vandamál, reyndu þá að endurræsa tölvuna."

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:5 ../gtk/apport-gtk.ui.h:5
msgid "Send an error report to help fix this problem"
msgstr "Senda villuskýrslu til að hjálpa til við lausn þessa vandamáls"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:6 ../gtk/apport-gtk.ui.h:6
msgid "Ignore future problems of this program version"
msgstr "Hunsa frekari vandamál í þessarri útgáfu forrits"

#: ../kde/apport-kde.py:278 ../gtk/apport-gtk.py:204 ../gtk/apport-gtk.py:573
#: ../debian/tmp/usr/share/apport/apport-kde.py:278
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:7
#: ../debian/tmp/usr/share/apport/apport-gtk.py:204
#: ../debian/tmp/usr/share/apport/apport-gtk.py:573 ../gtk/apport-gtk.ui.h:7
msgid "Show Details"
msgstr "Sýna ítarlegri upplýsingar"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:8 ../gtk/apport-gtk.ui.h:8
msgid "_Examine locally"
msgstr "Skoða _hér"

#: ../kde/apport-kde.py:220 ../gtk/apport-gtk.py:287
#: ../debian/tmp/usr/share/apport/apport-kde.py:220
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:9
#: ../debian/tmp/usr/share/apport/apport-gtk.py:287 ../gtk/apport-gtk.ui.h:9
msgid "Leave Closed"
msgstr "Skilja eftir lokað"

#: ../kde/apport-kde.py:217 ../kde/apport-kde.py:230
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:115
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:144
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:157
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:192
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:271
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:347
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:387
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:516
#: ../gtk/apport-gtk.py:216 ../gtk/apport-gtk.py:284 ../gtk/apport-gtk.py:303
#: ../debian/tmp/usr/share/apport/apport-kde.py:217
#: ../debian/tmp/usr/share/apport/apport-kde.py:230
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:10
#: ../debian/tmp/usr/share/apport/apport-gtk.py:216
#: ../debian/tmp/usr/share/apport/apport-gtk.py:284
#: ../debian/tmp/usr/share/apport/apport-gtk.py:303 ../gtk/apport-gtk.ui.h:10
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:115
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:141
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:153
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:186
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:267
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:298
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:368
msgid "Continue"
msgstr "Halda áfram"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:11 ../gtk/apport-gtk.ui.h:11
msgid "<big><b>Collecting problem information</b></big>"
msgstr "<big><b>Safna upplýsingum um vandamál</b></big>"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:12 ../gtk/apport-gtk.ui.h:12
msgid ""
"Information is being collected that may help the developers fix the problem "
"you report."
msgstr ""
"Er að safna upplýsingum sem gætu hjálpað forriturum að laga vandann sem þú "
"tilkynnir"

#: ../kde/apport-kde.py:422 ../debian/tmp/usr/share/apport/apport-kde.py:422
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:13 ../bin/apport-cli.py:251
#: ../gtk/apport-gtk.ui.h:13 ../debian/tmp/usr/bin/apport-cli.py:251
msgid "Uploading problem information"
msgstr "Sendi vandamálsskýrslu"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:14 ../gtk/apport-gtk.ui.h:14
msgid "<big><b>Uploading problem information</b></big>"
msgstr "<big><b>Sendi vandamálsskýrslu</b></big>"

#: ../kde/apport-kde.py:423 ../debian/tmp/usr/share/apport/apport-kde.py:423
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:15 ../gtk/apport-gtk.ui.h:15
msgid ""
"The collected information is being sent to the bug tracking system. This "
"might take a few minutes."
msgstr ""
"Er að senda upplýsingarnar á villukerfið. Þetta gæti tekið nokkrar mínútur."

#: ../kde/apport-kde-mimelnk.desktop.in.h:1
msgid "Apport crash file"
msgstr "Apport villuskrá"

#: ../kde/apport-kde.py:349 ../gtk/apport-gtk.py:142
#: ../debian/tmp/usr/share/apport/apport-kde.py:349 ../bin/apport-cli.py:150
#: ../debian/tmp/usr/share/apport/apport-gtk.py:142
#: ../debian/tmp/usr/bin/apport-cli.py:150
msgid "(binary data)"
msgstr "(gögn í tvíundakerfi)"

#: ../gtk/apport-gtk.py:157 ../debian/tmp/usr/share/apport/apport-gtk.py:157
#, python-format
msgid "Sorry, the application %s has stopped unexpectedly."
msgstr "Því miður, forritið %s hætti óvænt."

#: ../gtk/apport-gtk.py:160 ../debian/tmp/usr/share/apport/apport-gtk.py:160
#, python-format
msgid "Sorry, %s has closed unexpectedly."
msgstr "Því miður, forritið %s lokaði óvænt."

#: ../kde/apport-kde.py:183 ../kde/apport-kde.py:224
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:108
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:337
#: ../gtk/apport-gtk.py:165 ../debian/tmp/usr/share/apport/apport-kde.py:183
#: ../debian/tmp/usr/share/apport/apport-kde.py:224
#: ../debian/tmp/usr/share/apport/apport-gtk.py:165
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:110
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:290
#, python-format
msgid "Sorry, %s has experienced an internal error."
msgstr "Því miður, %s hefur lent í innri villu."

#: ../kde/apport-kde.py:169
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:441
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:466
#: ../gtk/apport-gtk.py:177 ../debian/tmp/usr/share/apport/apport-kde.py:169
#: ../bin/apport-cli.py:178 ../debian/tmp/usr/share/apport/apport-gtk.py:177
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:322
#: ../debian/tmp/usr/bin/apport-cli.py:178
msgid "Send problem report to the developers?"
msgstr "Senda vandamálsskýrslu til forritara?"

#: ../kde/apport-kde.py:177
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:449
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:474
#: ../gtk/apport-gtk.py:186 ../debian/tmp/usr/share/apport/apport-kde.py:177
#: ../debian/tmp/usr/share/apport/apport-gtk.py:186
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:328
msgid "Send"
msgstr "Senda"

#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:313
#: ../gtk/apport-gtk.py:228 ../debian/tmp/usr/share/apport/apport-gtk.py:228
msgid "Force Closed"
msgstr "Þvinga til að loka"

#: ../kde/apport-kde.py:221 ../kde/apport-kde.py:368
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:234
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:310
#: ../gtk/apport-gtk.py:229 ../gtk/apport-gtk.py:288
#: ../debian/tmp/usr/share/apport/apport-kde.py:221
#: ../debian/tmp/usr/share/apport/apport-kde.py:368
#: ../debian/tmp/usr/share/apport/apport-gtk.py:229
#: ../debian/tmp/usr/share/apport/apport-gtk.py:288
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:228
msgid "Relaunch"
msgstr "Keyra aftur upp"

#: ../gtk/apport-gtk.py:238 ../debian/tmp/usr/share/apport/apport-gtk.py:238
#, python-format
msgid "The application %s has stopped responding."
msgstr "Forritið %s hætti að svara."

#: ../gtk/apport-gtk.py:242 ../debian/tmp/usr/share/apport/apport-gtk.py:242
#, python-format
msgid "The program \"%s\" has stopped responding."
msgstr "Forritið %s hætti að svara."

#: ../kde/apport-kde.py:191 ../gtk/apport-gtk.py:257
#: ../debian/tmp/usr/share/apport/apport-kde.py:191
#: ../debian/tmp/usr/share/apport/apport-gtk.py:257
#, python-format
msgid "Package: %s"
msgstr "Pakki: %s"

#: ../kde/apport-kde.py:197
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:137
#: ../gtk/apport-gtk.py:264 ../debian/tmp/usr/share/apport/apport-kde.py:197
#: ../debian/tmp/usr/share/apport/apport-gtk.py:264
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:136
msgid "Sorry, a problem occurred while installing software."
msgstr "Því miður, vandamál kom upp við upppsetningu hugbúnaðar."

#: ../kde/apport-kde.py:204 ../gtk/apport-gtk.py:273 ../gtk/apport-gtk.py:292
#: ../debian/tmp/usr/share/apport/apport-kde.py:204
#: ../debian/tmp/usr/share/apport/apport-gtk.py:273
#: ../debian/tmp/usr/share/apport/apport-gtk.py:292
#, python-format
msgid "The application %s has experienced an internal error."
msgstr "Forritið %s lenti í innri villu."

#: ../kde/apport-kde.py:208 ../gtk/apport-gtk.py:276
#: ../debian/tmp/usr/share/apport/apport-kde.py:208
#: ../debian/tmp/usr/share/apport/apport-gtk.py:276
#, python-format
msgid "The application %s has closed unexpectedly."
msgstr "Forritið %s lokaði óvænt."

#: ../kde/apport-kde.py:231 ../gtk/apport-gtk.py:304
#: ../debian/tmp/usr/share/apport/apport-kde.py:231
#: ../debian/tmp/usr/share/apport/apport-gtk.py:304
msgid "Ignore future problems of this type"
msgstr "Hunsa svona vandamál héðan í frá"

#: ../kde/apport-kde.py:275 ../gtk/apport-gtk.py:577
#: ../debian/tmp/usr/share/apport/apport-kde.py:275
#: ../debian/tmp/usr/share/apport/apport-gtk.py:577
msgid "Hide Details"
msgstr "Fela nánari upplýsingar"

#: ../bin/apport-unpack.py:22 ../debian/tmp/usr/bin/apport-unpack.py:22
#, python-format
msgid "Usage: %s <report> <target directory>"
msgstr "Notkun: %s <report> <target directory>"

#: ../bin/apport-unpack.py:46 ../debian/tmp/usr/bin/apport-unpack.py:46
msgid "Destination directory exists and is not empty."
msgstr ""

#: ../kde/apport-kde.py:301 ../debian/tmp/usr/share/apport/apport-kde.py:301
msgid "Username:"
msgstr "Notandanafn:"

#: ../kde/apport-kde.py:302 ../debian/tmp/usr/share/apport/apport-kde.py:302
msgid "Password:"
msgstr "Lykilorð:"

#: ../kde/apport-kde.py:393 ../debian/tmp/usr/share/apport/apport-kde.py:393
msgid "Collecting Problem Information"
msgstr "Safna saman upplýsingum um vandamál"

#: ../kde/apport-kde.py:394 ../debian/tmp/usr/share/apport/apport-kde.py:394
#: ../bin/apport-cli.py:238 ../debian/tmp/usr/bin/apport-cli.py:238
msgid "Collecting problem information"
msgstr "Safna saman upplýsingum um vandamál"

#: ../kde/apport-kde.py:395 ../debian/tmp/usr/share/apport/apport-kde.py:395
msgid ""
"The collected information can be sent to the developers to improve the "
"application. This might take a few minutes."
msgstr ""
"Söfnuðum upplýsingum er hægt að koma til forritaranna til að bæta forritið. "
"Þetta gæti tekið nokkrar mínútur."

#: ../kde/apport-kde.py:421 ../debian/tmp/usr/share/apport/apport-kde.py:421
msgid "Uploading Problem Information"
msgstr "Sendi upplýsingar um vandamálið"

#: ../apport/com.ubuntu.apport.policy.in.h:1
msgid "Collect system information"
msgstr "Safna kerfisupplýsingum"

#: ../apport/com.ubuntu.apport.policy.in.h:2
msgid ""
"Authentication is required to collect system information for this problem "
"report"
msgstr ""
"Auðkenningar er krafist fyrir söfnun á kerfisupplýsingum fyrir þessa "
"villuskýrslu"

#: ../apport/com.ubuntu.apport.policy.in.h:3
msgid "System problem reports"
msgstr "Vandamálaskýrslur kerfis"

#: ../apport/com.ubuntu.apport.policy.in.h:4
msgid ""
"Please enter your password to access problem reports of system programs"
msgstr "Sláðu inn lykilorð til að fá aðgang að villuskýrslum kerfisforrita"

#: ../kde/apport-kde.desktop.in.h:1 ../kde/apport-kde-mime.desktop.in.h:1
#: ../gtk/apport-gtk.desktop.in.h:1
msgid "Report a problem..."
msgstr "Tilkynna vandamál..."

#: ../kde/apport-kde.desktop.in.h:2 ../kde/apport-kde-mime.desktop.in.h:2
#: ../gtk/apport-gtk.desktop.in.h:2
msgid "Report a malfunction to the developers"
msgstr "Tilkynna bilun til forritara"

#: ../bin/apport-valgrind.py:37 ../debian/tmp/usr/bin/apport-valgrind.py:37
msgid "See man page for details."
msgstr "Sjá nánar á man-síðu."

#: ../bin/apport-valgrind.py:43 ../debian/tmp/usr/bin/apport-valgrind.py:43
msgid "specify the log file name produced by valgrind"
msgstr ""

#: ../bin/apport-valgrind.py:46 ../debian/tmp/usr/bin/apport-valgrind.py:46
msgid ""
"reuse a previously created sandbox dir (SDIR) or, if it does not exist, "
"create it"
msgstr ""
"endurnýta sandkassamöppu (SDIR) sem þegar hefur verið búin til eða, ef hún "
"er ekki til, búa hana til"

#: ../bin/apport-valgrind.py:50 ../debian/tmp/usr/bin/apport-valgrind.py:50
msgid ""
"do  not  create  or reuse a sandbox directory for additional debug symbols "
"but rely only on installed debug symbols."
msgstr ""
"ekki búa til né endurnýta sandkassamöppu fyrir auka aflúsunarmerki heldur "
"aðeins treysta á uppsett aflúsunarmerki."

#: ../bin/apport-valgrind.py:54 ../debian/tmp/usr/bin/apport-valgrind.py:54
msgid ""
"reuse a previously created cache dir (CDIR) or, if it does not exist, create "
"it"
msgstr ""
"endurnýta skyndiminnismöppu (CDIR) sem þegar hefur verið búin til eða, ef "
"hún er ekki til, búa hana til"

#: ../bin/apport-valgrind.py:58 ../debian/tmp/usr/bin/apport-valgrind.py:58
msgid ""
"report download/install progress when installing packages into sandbox"
msgstr ""

#: ../bin/apport-valgrind.py:62 ../debian/tmp/usr/bin/apport-valgrind.py:62
msgid ""
"the executable that is run under valgrind's memcheck tool  for memory leak "
"detection"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:59 ../bin/apport-retrace.py:59
#: ../bin/apport-valgrind.py:66 ../debian/tmp/usr/bin/apport-valgrind.py:66
msgid ""
"Install an extra package into the sandbox (can be specified multiple times)"
msgstr ""

#: ../bin/apport-valgrind.py:97 ../debian/tmp/usr/bin/apport-valgrind.py:97
#, python-format
msgid "Error: %s is not an executable. Stopping."
msgstr "Villa: %s er ekki keyranlegt forrit. Hætti."

#: ../debian/tmp/usr/share/apport/kernel_oops.py:30 ../data/kernel_oops.py:30
msgid "Your system might become unstable now and might need to be restarted."
msgstr ""
"Kerfið þitt verður kannski óstöðugt núna og þarf hugsanlega að endurræsa það."

#: ../debian/tmp/usr/bin/apport-retrace.py:33 ../bin/apport-retrace.py:33
msgid "Do not put the new traces into the report, but write them to stdout."
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:35 ../bin/apport-retrace.py:35
msgid ""
"Start an interactive gdb session with the report's core dump (-o ignored; "
"does not rewrite report)"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:37 ../bin/apport-retrace.py:37
msgid ""
"Write modified report to given file instead of changing the original report"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:39 ../bin/apport-retrace.py:39
msgid "Remove the core dump from the report after stack trace regeneration"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:41 ../bin/apport-retrace.py:41
msgid "Override report's CoreFile"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:43 ../bin/apport-retrace.py:43
msgid "Override report's ExecutablePath"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:45 ../bin/apport-retrace.py:45
msgid "Override report's ProcMaps"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:47 ../bin/apport-retrace.py:47
msgid "Rebuild report's Package information"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:49 ../bin/apport-retrace.py:49
msgid ""
"Build a temporary sandbox and download/install the necessary packages and "
"debug symbols in there; without this option it assumes that the necessary "
"packages and debug symbols are already installed in the system. The argument "
"points to the packaging system configuration base directory; if you specify "
"\"system\", it will use the system configuration files, but will then only "
"be able to retrace crashes that happened on the currently running release."
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:51 ../bin/apport-retrace.py:51
msgid ""
"Report download/install progress when installing packages into sandbox"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:53 ../bin/apport-retrace.py:53
msgid "Prepend timestamps to log messages, for batch operation"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:57 ../bin/apport-retrace.py:57
msgid ""
"Create and use third-party repositories from origins specified in reports"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:55 ../bin/apport-retrace.py:55
msgid "Cache directory for packages downloaded in the sandbox"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:57 ../bin/apport-retrace.py:57
msgid ""
"Directory for unpacked packages. Future runs will assume that any already "
"downloaded package is also extracted to this sandbox."
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:61 ../bin/apport-retrace.py:61
msgid ""
"Path to a file with the crash database authentication information. This is "
"used when specifying a crash ID to upload the retraced stack traces (only if "
"neither -g, -o, nor -s are specified)"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:63 ../bin/apport-retrace.py:63
msgid ""
"Display retraced stack traces and ask for confirmation before sending them "
"to the crash database."
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:65 ../bin/apport-retrace.py:65
msgid ""
"Path to the duplicate sqlite database (default: no duplicate checking)"
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:76 ../bin/apport-retrace.py:76
msgid "You cannot use -C without -S. Stopping."
msgstr "Þú getur ekki notað -C án -S. Hætti."

#. translators: don't translate y/n, apport currently only checks for "y"
#: ../debian/tmp/usr/bin/apport-retrace.py:114 ../bin/apport-retrace.py:114
msgid "OK to send these as attachments? [y/n]"
msgstr "Er allt í lagi að senda þetta sem sem viðhengi? [y/n]"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:125
#: ../apport/ui.py:125
msgid "This package does not seem to be installed correctly"
msgstr "Þessi pakki virðist ekki rétt upp settur"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:130
#: ../apport/ui.py:130
#, python-format
msgid ""
"This is not an official %s package. Please remove any third party package "
"and try again."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:147
#: ../apport/ui.py:147
#, python-format
msgid ""
"You have some obsolete package versions installed. Please upgrade the "
"following packages and check if the problem still occurs:\n"
"\n"
"%s"
msgstr ""
"Þú er með uppsettar einhverjar úreltar útgáfur af pökkum. Endilega uppfærðu "
"eftirfarandi pakka og athugaðu hvort vandamálið endurtekur sig:\n"
"\n"
"%s"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:275
#: ../apport/ui.py:275
msgid "unknown program"
msgstr "óþekkt forrit"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:276
#: ../apport/ui.py:276
#, python-format
msgid "Sorry, the program \"%s\" closed unexpectedly"
msgstr "Fyrirgefðu, forritið \"%s\" hætti óvænt"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:278
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1312
#: ../apport/ui.py:278 ../apport/ui.py:1312
#, python-format
msgid "Problem in %s"
msgstr "Vandamál í %s"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:279
#: ../apport/ui.py:279
msgid ""
"Your computer does not have enough free memory to automatically analyze the "
"problem and send a report to the developers."
msgstr ""
"Tölvan þín hefur ekki nóg laust innra minni til að greina sjálfkrafa "
"vandamálið og senda til forritaranna."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:327
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:335
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:462
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:465
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:666
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1118
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1284
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1288
#: ../apport/ui.py:327 ../apport/ui.py:335 ../apport/ui.py:462
#: ../apport/ui.py:465 ../apport/ui.py:666 ../apport/ui.py:1118
#: ../apport/ui.py:1284 ../apport/ui.py:1288
#: ../debian/tmp/usr/share/apport/testsuite/test_ui.py:276
#: ../debian/tmp/usr/share/apport/testsuite/test_ui.py:1137
msgid "Invalid problem report"
msgstr "Ógild vandamálsskýrsla"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:328
#: ../apport/ui.py:328
msgid "You are not allowed to access this problem report."
msgstr "Þú hefur ekki leyfi til að skoða þessa skýrslu."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:331
#: ../apport/ui.py:331
msgid "Error"
msgstr "Villa"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:332
#: ../apport/ui.py:332
msgid "There is not enough disk space available to process this report."
msgstr "Það er ekki nóg diskpláss til að vinna úr skýrslunni."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:416
#: ../apport/ui.py:416
msgid "No package specified"
msgstr "Enginn pakki valinn"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:417
#: ../apport/ui.py:417
msgid ""
"You need to specify a package or a PID. See --help for more information."
msgstr ""
"Þú þarft að tilgreina pakka eða PID. Sjá --help fyrir meiri upplýsingar."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:440
#: ../apport/ui.py:440
msgid "Permission denied"
msgstr "Aðgangur bannaður"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:441
#: ../apport/ui.py:441
msgid ""
"The specified process does not belong to you. Please run this program as the "
"process owner or as root."
msgstr ""
"Tiltekið ferli tilheyrir þér ekki. Keyrðu þetta forrit sem eigandi ferlisins "
"eða sem kerfisstjórnandi"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:443
#: ../apport/ui.py:443
msgid "Invalid PID"
msgstr "Ógilt PID"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:444
#: ../apport/ui.py:444
msgid "The specified process ID does not belong to a program."
msgstr "Þetta ID tilheyrir ekki neinu forriti."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:463
#: ../apport/ui.py:463
#, python-format
msgid "Symptom script %s did not determine an affected package"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:466
#: ../apport/ui.py:466
#, python-format
msgid "Package %s does not exist"
msgstr "Pakki %s er ekki til"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:490
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:678
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:683
#: ../apport/ui.py:490 ../apport/ui.py:678 ../apport/ui.py:683
msgid "Cannot create report"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:505
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:551
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:568
#: ../apport/ui.py:505 ../apport/ui.py:551 ../apport/ui.py:568
msgid "Updating problem report"
msgstr "Uppfæri villuskýrslu"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:506
#: ../apport/ui.py:506
msgid ""
"You are not the reporter or subscriber of this problem report, or the report "
"is a duplicate or already closed.\n"
"\n"
"Please create a new report using \"apport-bug\"."
msgstr ""
"Þú ert ekki tilkynnandi eða áskrifandi að þessarri villuskýrslu, eða "
"skýrslan er tvítekin eða nú þegar lokuð.\n"
"\n"
"Búðu til nýja skýrslu með ‚apport-bug‘."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:515
#: ../apport/ui.py:515
msgid ""
"You are not the reporter of this problem report. It is much easier to mark a "
"bug as a duplicate of another than to move your comments and attachments to "
"a new bug.\n"
"\n"
"Subsequently, we recommend that you file a new bug report using \"apport-"
"bug\" and make a comment in this bug about the one you file.\n"
"\n"
"Do you really want to proceed?"
msgstr ""
"Þú ert ekki tilkynnandi þessarar villuskýrslu. Mun auðveldara er að merkja "
"villu sem tvítekningu annarrar heldur en að færa athugasemdir og viðhengin "
"þín í nýja villu.\n"
"\n"
"Þar af leiðir ráðleggjum við að þú sendir inn nýja villuskýrslu með ‚apport-"
"bug‘ og búir til athugasemd í þessarri villu um þá skýrslu.\n"
"\n"
"Ertu alveg viss þú viljir halda áfram?"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:552
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:569
#: ../apport/ui.py:552 ../apport/ui.py:569
msgid "No additional information collected."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:620
#: ../apport/ui.py:620
msgid "What kind of problem do you want to report?"
msgstr "Hvers konar forrit viltu senda skýrslu um?"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:637
#: ../apport/ui.py:637
msgid "Unknown symptom"
msgstr "Óþekkt einkenni"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:638
#: ../apport/ui.py:638
#, python-format
msgid "The symptom \"%s\" is not known."
msgstr "Einkennið „%s“ er ekki þekkt."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:669
#: ../apport/ui.py:669
msgid ""
"After closing this message please click on an application window to report a "
"problem about it."
msgstr ""
"Eftir lokun þessa skilaboða, smelltu á forritsglugga til að skrá villu um "
"hann."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:679
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:684
#: ../apport/ui.py:679 ../apport/ui.py:684
msgid "xprop failed to determine process ID of the window"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:698
#: ../apport/ui.py:698
msgid "%prog <report number>"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:700
#: ../apport/ui.py:700
msgid "Specify package name."
msgstr "Tilgreindu pakkaheiti."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:702
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:753
#: ../apport/ui.py:702 ../apport/ui.py:753
msgid "Add an extra tag to the report. Can be specified multiple times."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:732
#: ../apport/ui.py:732
msgid ""
"%prog [options] [symptom|pid|package|program path|.apport/.crash file]"
msgstr ""
"%prog [options] [symptom|pid|package|program path|.apport/.crash file]"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:735
#: ../apport/ui.py:735
msgid ""
"Start in bug filing mode. Requires --package and an optional --pid, or just "
"a --pid. If neither is given, display a list of known symptoms. (Implied if "
"a single argument is given.)"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:737
#: ../apport/ui.py:737
msgid "Click a window as a target for filing a problem report."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:739
#: ../apport/ui.py:739
msgid "Start in bug updating mode. Can take an optional --package."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:741
#: ../apport/ui.py:741
msgid ""
"File a bug report about a symptom. (Implied if symptom name is given as only "
"argument.)"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:743
#: ../apport/ui.py:743
msgid ""
"Specify package name in --file-bug mode. This is optional if a --pid is "
"specified. (Implied if package name is given as only argument.)"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:745
#: ../apport/ui.py:745
msgid ""
"Specify a running program in --file-bug mode. If this is specified, the bug "
"report will contain more information.  (Implied if pid is given as only "
"argument.)"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:747
#: ../apport/ui.py:747
msgid "The provided pid is a hanging application."
msgstr "Gefna PID-ið er forrit sem hangir."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:749
#: ../apport/ui.py:749
#, python-format
msgid ""
"Report the crash from given .apport or .crash file instead of the pending "
"ones in %s. (Implied if file is given as only argument.)"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:751
#: ../apport/ui.py:751
msgid ""
"In bug filing mode, save the collected information into a file instead of "
"reporting it. This file can then be reported later on from a different "
"machine."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:755
#: ../apport/ui.py:755
msgid "Print the Apport version number."
msgstr "Gefa Apport útgáfunúmerið."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:895
#: ../apport/ui.py:895
msgid ""
"This will launch apport-retrace in a terminal window to examine the crash."
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:896
#: ../apport/ui.py:896
msgid "Run gdb session"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:897
#: ../apport/ui.py:897
msgid "Run gdb session without downloading debug symbols"
msgstr ""

#. TRANSLATORS: %s contains the crash report file name
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:899
#: ../apport/ui.py:899
#, python-format
msgid "Update %s with fully symbolic stack trace"
msgstr ""

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:975
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:985
#: ../apport/ui.py:975 ../apport/ui.py:985
msgid ""
"This problem report applies to a program which is not installed any more."
msgstr "Þessi vandamálaskýrsla á við forrit sem er ekki uppsett lengur."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1000
#: ../apport/ui.py:1000
#, python-format
msgid ""
"The problem happened with the program %s which changed since the crash "
"occurred."
msgstr ""
"Vandamálið kom fyrir í forritunu %s sem er breytt síðan síðasta hrun varð."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1047
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1290
#: ../apport/ui.py:1047 ../apport/ui.py:1290
msgid "This problem report is damaged and cannot be processed."
msgstr "Skýrslan er löskuð og ég get ekki unnið úr henni"

#. package does not exist
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1051
#: ../apport/ui.py:1051
msgid "The report belongs to a package that is not installed."
msgstr "Þessi skýrsla tilheyrir pakka sem ekki er uppsettur"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1055
#: ../apport/ui.py:1055
msgid "An error occurred while attempting to process this problem report:"
msgstr "Villa kom upp þegar reynt var að vinna þessa villuskýrslu:"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1119
#: ../apport/ui.py:1119
msgid "Could not determine the package or source package name."
msgstr "Gat ekki ákveðið nafn pakka eða grunnpakka"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1137
#: ../apport/ui.py:1137
msgid "Unable to start web browser"
msgstr "Gat ekki ræst vefvafra"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1138
#: ../apport/ui.py:1138
#, python-format
msgid "Unable to start web browser to open %s."
msgstr "Gat ekki ræst vefvafra til að opna %s"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1238
#: ../apport/ui.py:1238
#, python-format
msgid "Please enter your account information for the %s bug tracking system"
msgstr "Sláðu inn aðgangsupplýsingar þínar fyrir %s villukerfið."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1250
#: ../apport/ui.py:1250
msgid "Network problem"
msgstr "Vandamál með nettengingu"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1252
#: ../apport/ui.py:1252
msgid ""
"Cannot connect to crash database, please check your Internet connection."
msgstr "Get ekki tengst við gagnagrunn, athugaðu nettenginguna."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1279
#: ../apport/ui.py:1279
msgid "Memory exhaustion"
msgstr "Minnisvandamál"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1280
#: ../apport/ui.py:1280
msgid "Your system does not have enough memory to process this crash report."
msgstr ""
"Kerfið þitt hefur ekki nóg vinnsluminni til að vinna úr þessari skýrslu."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1315
#: ../apport/ui.py:1315
#, python-format
msgid ""
"The problem cannot be reported:\n"
"\n"
"%s"
msgstr ""
"Ekki hægt að tilkynna vandamálið:\n"
"\n"
"%s"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1371
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1378
#: ../apport/ui.py:1371 ../apport/ui.py:1378
msgid "Problem already known"
msgstr "Vandamál þegar þekkt"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1372
#: ../apport/ui.py:1372
msgid ""
"This problem was already reported in the bug report displayed in the web "
"browser. Please check if you can add any further information that might be "
"helpful for the developers."
msgstr ""
"Þetta vandamál var þegar tilkynnt í villuskýrslunni sem birtist í "
"vefvafranum. Athugaðu hvort þú getur bætt við einhverjum gagnlegum "
"upplýsingum."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1379
#: ../apport/ui.py:1379
msgid "This problem was already reported to developers. Thank you!"
msgstr ""
"Þetta vandamál hefur nú þegar verið tilkynnt til þróunarteymis. Takk fyrir!"

#: ../debian/tmp/usr/share/apport/apportcheckresume.py:67
#: ../data/apportcheckresume.py:67
msgid ""
"This occurred during a previous suspend, and prevented the system from "
"resuming properly."
msgstr ""

#: ../debian/tmp/usr/share/apport/apportcheckresume.py:69
#: ../data/apportcheckresume.py:69
msgid ""
"This occurred during a previous hibernation, and prevented the system from "
"resuming properly."
msgstr ""

#: ../debian/tmp/usr/share/apport/apportcheckresume.py:80
#: ../data/apportcheckresume.py:80
msgid ""
"The resume processing hung very near the end and will have appeared to have "
"completed normally."
msgstr ""
"Endurvakningin hékk í blá endann en lítur út fyrir að hafa klárast eðlilega."

#: ../bin/apport-cli.py:74 ../debian/tmp/usr/bin/apport-cli.py:74
msgid "Press any key to continue..."
msgstr "Ýttu á einhvern lykil til að halda áfram..."

#: ../bin/apport-cli.py:81 ../debian/tmp/usr/bin/apport-cli.py:81
msgid "What would you like to do? Your options are:"
msgstr "Hvað viltu gera? Þú getur:"

#: ../bin/apport-cli.py:85 ../debian/tmp/usr/bin/apport-cli.py:85
#, python-format
msgid "Please choose (%s):"
msgstr "Veldu (%s);"

#: ../bin/apport-cli.py:148 ../debian/tmp/usr/bin/apport-cli.py:148
#, python-format
msgid "(%i bytes)"
msgstr "(%i bæti)"

#: ../bin/apport-cli.py:179 ../debian/tmp/usr/bin/apport-cli.py:179
msgid ""
"After the problem report has been sent, please fill out the form in the\n"
"automatically opened web browser."
msgstr ""
"Eftir að vandamálaskýrslan hefur verið send opnast sjálfkrafa netvafri með "
"formi.\n"
"Vinsamlegast fylltu það út."

#: ../bin/apport-cli.py:182 ../debian/tmp/usr/bin/apport-cli.py:182
#, python-format
msgid "&Send report (%s)"
msgstr "&Senda skýrslu (%s)"

#: ../bin/apport-cli.py:186 ../debian/tmp/usr/bin/apport-cli.py:186
msgid "&Examine locally"
msgstr "Skoða &hér"

#: ../bin/apport-cli.py:190 ../debian/tmp/usr/bin/apport-cli.py:190
msgid "&View report"
msgstr "&Lesa skýrslu"

#: ../bin/apport-cli.py:191 ../debian/tmp/usr/bin/apport-cli.py:191
msgid "&Keep report file for sending later or copying to somewhere else"
msgstr "&Geyma skýrslu til að senda inn seinna eða til að færa á annan stað"

#: ../bin/apport-cli.py:192 ../debian/tmp/usr/bin/apport-cli.py:192
msgid "Cancel and &ignore future crashes of this program version"
msgstr "Hætta við og h&unsa frekari hrun í þessari útgáfu forritsins"

#: ../bin/apport-cli.py:194 ../bin/apport-cli.py:271 ../bin/apport-cli.py:303
#: ../bin/apport-cli.py:324 ../debian/tmp/usr/bin/apport-cli.py:194
#: ../debian/tmp/usr/bin/apport-cli.py:271
#: ../debian/tmp/usr/bin/apport-cli.py:303
#: ../debian/tmp/usr/bin/apport-cli.py:324
msgid "&Cancel"
msgstr "&Hætta við"

#: ../bin/apport-cli.py:222 ../debian/tmp/usr/bin/apport-cli.py:222
msgid "Problem report file:"
msgstr "Skrá með upplýsingar um vandamál:"

#: ../bin/apport-cli.py:228 ../bin/apport-cli.py:233
#: ../debian/tmp/usr/bin/apport-cli.py:228
#: ../debian/tmp/usr/bin/apport-cli.py:233
msgid "&Confirm"
msgstr "&Staðfesta"

#: ../bin/apport-cli.py:232 ../debian/tmp/usr/bin/apport-cli.py:232
#, python-format
msgid "Error: %s"
msgstr "Villa: %s"

#: ../bin/apport-cli.py:239 ../debian/tmp/usr/bin/apport-cli.py:239
msgid ""
"The collected information can be sent to the developers to improve the\n"
"application. This might take a few minutes."
msgstr ""
"Þú getur sent inn skýrslu með þessum upplýsingum til að bæta forritið.\n"
"Þetta getur tekið nokkra stund."

#: ../bin/apport-cli.py:252 ../debian/tmp/usr/bin/apport-cli.py:252
msgid ""
"The collected information is being sent to the bug tracking system.\n"
"This might take a few minutes."
msgstr ""
"Verið er að senda upplýsingar sem safnað hefur verið í villukerfi.\n"
"Það getur tekið nokkrar mínútur."

#: ../bin/apport-cli.py:302 ../debian/tmp/usr/bin/apport-cli.py:302
msgid "&Done"
msgstr "&Lokið"

#: ../bin/apport-cli.py:308 ../debian/tmp/usr/bin/apport-cli.py:308
msgid "none"
msgstr "ekkert"

#: ../bin/apport-cli.py:309 ../debian/tmp/usr/bin/apport-cli.py:309
#, python-format
msgid "Selected: %s. Multiple choices:"
msgstr "Valið: %s. Margir valkostir:"

#: ../bin/apport-cli.py:325 ../debian/tmp/usr/bin/apport-cli.py:325
msgid "Choices:"
msgstr "Valkostir:"

#: ../bin/apport-cli.py:339 ../debian/tmp/usr/bin/apport-cli.py:339
msgid "Path to file (Enter to cancel):"
msgstr "Slóð skráar (Enter til að hætta við):"

#: ../bin/apport-cli.py:345 ../debian/tmp/usr/bin/apport-cli.py:345
msgid "File does not exist."
msgstr "Skrá er ekki til."

#: ../bin/apport-cli.py:347 ../debian/tmp/usr/bin/apport-cli.py:347
msgid "This is a directory."
msgstr "Þetta er mappa."

#: ../bin/apport-cli.py:353 ../debian/tmp/usr/bin/apport-cli.py:353
msgid "To continue, you must visit the following URL:"
msgstr "Þú verður að heimsækja eftirfarandi slóð til að halda áfram:"

#: ../bin/apport-cli.py:355 ../debian/tmp/usr/bin/apport-cli.py:355
msgid ""
"You can launch a browser now, or copy this URL into a browser on another "
"computer."
msgstr ""
"Þú getur ræst vafra núna eða afritað þessa slóð í vafra á annari tölvu."

#: ../bin/apport-cli.py:357 ../debian/tmp/usr/bin/apport-cli.py:357
msgid "Launch a browser now"
msgstr "Ræsa netvafra"

#: ../bin/apport-cli.py:371 ../debian/tmp/usr/bin/apport-cli.py:371
msgid "No pending crash reports. Try --help for more information."
msgstr ""

#, no-c-format, python-format
#~ msgid "Complete report (recommended; %s)"
#~ msgstr "Full skýrsla (mælt með; %s)"

#~ msgid ""
#~ "<big><b>Send problem report to the developers?</b></big>\n"
#~ "\n"
#~ "After the problem report has been sent, please fill out the form in the "
#~ "automatically opened web browser."
#~ msgstr ""
#~ "<big><b>Senda vandamálsskýrslu til forritaranna?</b></big>\n"
#~ "\n"
#~ "Eftir að skýrslan hefur verið send, vinsamlegast fylltu út formið í vafranum "
#~ "sem opnast sjálfkrafa."

#~ msgid ""
#~ "If you were not doing anything confidential (entering passwords or other "
#~ "private information), you can help to improve the application by reporting "
#~ "the problem."
#~ msgstr ""
#~ "Ef þú varst ekki að gera eitthvað leynilegt (slá inn lykilorð eða aðrar "
#~ "persónulegar upplýsingar) geturðu hjálpað við að bæta forritið með því að "
#~ "tilkynna vandamálið."

#~ msgid "Application problem"
#~ msgstr "Forritsvandamál"

#~ msgid "_Send Report"
#~ msgstr "_Senda skýrslu"

#~ msgid ""
#~ "If you were not doing anything confidential (entering passwords or other\n"
#~ "private information), you can help to improve the application by reporting\n"
#~ "the problem."
#~ msgstr ""
#~ "Ef þú varst ekki að gera eitthvað persónugreinanlegt (slá inn lykilorð eða \n"
#~ "aðrar persónulegar upplýsingar) getur þú hjálpað við að laga forritið með\n"
#~ "því að tilkynna vandamálið."

#~ msgid "Restart _Program"
#~ msgstr "_Endurræsa Forrit"

#, no-c-format
#~ msgid ""
#~ "<span weight=\"bold\" size=\"larger\">Sorry, the package \"%s\" failed to "
#~ "install or upgrade.</span>"
#~ msgstr ""
#~ "<span weight=\"bold\" size=\"larger\">Því miður tókst ekki að setja upp eða "
#~ "uppfæra pakkann \"%s\"</span>"

#, no-c-format, python-format
#~ msgid "Reduced report (slow Internet connection; %s)"
#~ msgstr "Minnkuð skýrsla (hæg nettenging; %s)"

#~ msgid "_Ignore future crashes of this program version"
#~ msgstr "_Hunsa frekari hrun þessarar forritsútgáfu"

#~ msgid ""
#~ "This will remove some large items from the report. These are very useful for "
#~ "developers to debug the problem, but might be too big for you to upload if "
#~ "you have a slow internet connection."
#~ msgstr ""
#~ "Þetta tekur nokkra stóra hluta úr skýrslunni. Þeir eru gagnlegir forriturum "
#~ "til að greina vandamálkið, en gætu verið of stórir til að að senda yfir hæga "
#~ "nettengingu."

#~ msgid "&Report Problem..."
#~ msgstr "&Tilkynna vandamál"

#~ msgid "_Report Problem..."
#~ msgstr "_Tilkynna vandamál..."

#~ msgid "Kernel problem"
#~ msgstr "Kjarnavandi"

#~ msgid ""
#~ "You can help the developers to fix the package by reporting the problem."
#~ msgstr ""
#~ "Þú getur hjálpað forriturunum að laga pakkann með því að senda inn "
#~ "tilkynningu."

#, python-format
#~ msgid "This is not a genuine %s package"
#~ msgstr "Þetta er ekki alvöru %s pakki"

#~ msgid "Content of the report"
#~ msgstr "Innihald skýrslunnar"

#~ msgid "Package problem"
#~ msgstr "Pakkavandamál"

#, python-format
#~ msgid "The package \"%s\" failed to install or upgrade."
#~ msgstr "Það tókst hvorki að setja upp “%s“ eða uppfæra."

#, python-format
#~ msgid "%s closed unexpectedly on %s at %s."
#~ msgstr "%s lokaði óviðbúið þann %s klukkan %s."

#~ msgid "Your system encountered a serious kernel problem."
#~ msgstr "Kerfið þitt lenti í alvarlegum vanda með stýrikerfiskjarnann"

#~ msgid "You can help the developers to fix the problem by reporting it."
#~ msgstr "Þú getur hjálpað til með því að tilkynna vandann."

#, python-format
#~ msgid "&Send complete report (recommended; %s)"
#~ msgstr "&Senda alla skýrsluna (mælt með þessu; %s)"

#, python-format
#~ msgid "Send &reduced report (slow Internet connection; %s)"
#~ msgstr "Senda &stytta skýrslu (hæg nettenging; %s)"

#~ msgid "%prog [options] <apport problem report | crash ID>"
#~ msgstr "%prog [options] <apport problem report | crash ID>"

#~ msgid ""
#~ "This occured during a previous suspend and prevented it from resuming "
#~ "properly."
#~ msgstr ""
#~ "Þetta gerðist áður meðan verið var í svæfingu og kom í veg fyrir "
#~ "endurvakningu úr því ástandi."

#~ msgid ""
#~ "This occured during a previous hibernate and prevented it from resuming "
#~ "properly."
#~ msgstr ""
#~ "Þetta gerðist áður meðan verið var í dvala og kom í veg fyrir endurvakningu "
#~ "úr því ástandi."
