# Uighur translation for apport
# Copyright (c) 2009 Rosetta Contributors and Canonical Ltd 2009
# This file is distributed under the same license as the apport package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2009.
#
msgid ""
msgstr ""
"Project-Id-Version: apport\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2012-10-01 11:58+0200\n"
"PO-Revision-Date: 2012-11-05 05:13+0000\n"
"Last-Translator: bilgeturghun <bilgeks@gmail.com>\n"
"Language-Team: Uighur <ug@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2012-11-06 04:31+0000\n"
"X-Generator: Launchpad (build 16232)\n"
"Language: ug\n"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:105
#: ../apport/ui.py:105
msgid "This package does not seem to be installed correctly"
msgstr "مەزكۇر بوغچا توغرا ئورنىتىلمىغاندەك قىلىدۇ"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:109
#: ../apport/ui.py:109
#, python-format
msgid ""
"This is not an official %s package. Please remove any third party package "
"and try again."
msgstr ""
"بۇ رەسمىي %s بوغچىسى ئەمەس. ئۈچىنچى تەرەپ بوغچىسىنى چىقىرىۋېتىپ، قايتا سىناڭ."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:126
#: ../apport/ui.py:126
#, python-format
msgid ""
"You have some obsolete package versions installed. Please upgrade the "
"following packages and check if the problem still occurs:\n"
"\n"
"%s"
msgstr ""
"بەزىبىر كونا بوغچىلار بار ئىكەن. تۆۋەندىكى بوغچىلارنى يۈكسەلدۈرگەندىن كېيىن "
"يەنە تەكشۈرۈپ كۆرۈڭ:\n"
"\n"
"%s"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:232
#: ../apport/ui.py:232
msgid "unknown program"
msgstr "نامەلۇم پروگرامما"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:233
#: ../apport/ui.py:233
#, python-format
msgid "Sorry, the program \"%s\" closed unexpectedly"
msgstr "كەچۈرۈڭ، پروگرامما  «%s» ئويلىمىغان يەردىن تاقىلىپ قالدى"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:235
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1237
#: ../apport/ui.py:235 ../apport/ui.py:1237
#, python-format
msgid "Problem in %s"
msgstr "مەسىلە %s نىڭدا"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:236
#: ../apport/ui.py:236
msgid ""
"Your computer does not have enough free memory to automatically analyze the "
"problem and send a report to the developers."
msgstr ""
"مەسىلىنى ئاپتوماتىك ئانالىز قىلىش ۋە ئىجادىيەتچىگە مەلۇمات يوللاشقا كېرەكلىك "
"ئەسلەك يېتەرلىك ئەمەس ئىكەن."

#. package does not exist
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:251
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:257
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:263
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:306
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:314
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:443
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:446
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:647
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1050
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1191
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1195
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1214
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1220
#: ../apport/ui.py:251 ../apport/ui.py:257 ../apport/ui.py:263
#: ../apport/ui.py:306 ../apport/ui.py:314 ../apport/ui.py:443
#: ../apport/ui.py:446 ../apport/ui.py:647 ../apport/ui.py:1050
#: ../apport/ui.py:1191 ../apport/ui.py:1195 ../apport/ui.py:1214
#: ../apport/ui.py:1220
#: ../debian/tmp/usr/share/apport/testsuite/test_ui.py:268
#: ../debian/tmp/usr/share/apport/testsuite/test_ui.py:285
#: ../debian/tmp/usr/share/apport/testsuite/test_ui.py:1052
#: ../debian/tmp/usr/share/apport/testsuite/test_ui.py:1072
#: ../debian/tmp/usr/share/apport/testsuite/test_ui.py:1083
#: ../debian/tmp/usr/share/apport/testsuite/test_ui.py:1094
msgid "Invalid problem report"
msgstr "مەلۇمات ئىناۋەتسىز"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:252
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1197
#: ../apport/ui.py:252 ../apport/ui.py:1197
msgid "This problem report is damaged and cannot be processed."
msgstr "بوغچا بۇزۇلغان بولغاچقا بىر تەرەپ قىلغىلى بولمىدى."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:258
#: ../apport/ui.py:258
msgid "The report belongs to a package that is not installed."
msgstr "مەلۇمات ئورنىتىلمىغان بوغچىغا تەۋە ئىكەن."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:264
#: ../apport/ui.py:264
msgid "An error occurred while attempting to process this problem report:"
msgstr ""
"بۇ مەسىلە ھەققىدىكى مەلۇماتنى بىر تەرەپ قىلاي دېگەندە  خاتالىق يۈز بەردى:"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:307
#: ../apport/ui.py:307
msgid "You are not allowed to access this problem report."
msgstr "بۇ مەسىلىنى مەلۇم قىلىش ھوقۇقىڭىز يوق."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:310
#: ../apport/ui.py:310
msgid "Error"
msgstr "خاتالىق"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:311
#: ../apport/ui.py:311
msgid "There is not enough disk space available to process this report."
msgstr "مەزكۇر مەلۇماتنى بىر تەرەپ قىلىشقا كېرەكلىك دىسكا بوشلۇقى يوق."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:395
#: ../apport/ui.py:395
msgid "No package specified"
msgstr "بوغچا كۆرسىتىلمىگەن."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:396
#: ../apport/ui.py:396
msgid ""
"You need to specify a package or a PID. See --help for more information."
msgstr ""
"بوغچا ياكى بىر PID نى كۆرسىتىڭ. تەپسىلاتلار ئۈچۈن --help نى ئىشلىتىڭ."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:413
#: ../apport/ui.py:413
msgid "Invalid PID"
msgstr "ئىناۋەتسىز PID"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:414
#: ../apport/ui.py:414
msgid "The specified process ID does not belong to a program."
msgstr "كۆرسىتىلگەن PID مەزكۇر پروگراممىنىڭ PID ئەمەس."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:422
#: ../apport/ui.py:422
msgid "Permission denied"
msgstr "ھوقۇقىڭىز يەتمىدى"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:423
#: ../apport/ui.py:423
msgid ""
"The specified process does not belong to you. Please run this program as the "
"process owner or as root."
msgstr ""
"بۇ سىزنىڭ پروگراممىڭىز ئەمەس. مەزكۇر پروگراممىنى ئۆزىڭىزنىڭ ياكى root نىڭ "
"ھوقۇقىدا ئىجرا قىلدۇرۇڭ."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:444
#: ../apport/ui.py:444
#, python-format
msgid "Symptom script %s did not determine an affected package"
msgstr "ئەھۋال قوليازما %s تەسىر كۆرسىتىدىغان بوغچىنى بەلگىلىمىگەن"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:447
#: ../apport/ui.py:447
#, python-format
msgid "Package %s does not exist"
msgstr "بوغچا %s مەۋجۇت ئەمەس"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:471
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:659
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:664
#: ../apport/ui.py:471 ../apport/ui.py:659 ../apport/ui.py:664
msgid "Cannot create report"
msgstr "مەلۇمات قۇرالمىدى"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:486
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:532
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:549
#: ../apport/ui.py:486 ../apport/ui.py:532 ../apport/ui.py:549
msgid "Updating problem report"
msgstr "مەلۇماتىنى يېڭىلاۋاتىدۇ"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:487
#: ../apport/ui.py:487
msgid ""
"You are not the reporter or subscriber of this problem report, or the report "
"is a duplicate or already closed.\n"
"\n"
"Please create a new report using \"apport-bug\"."
msgstr ""
"سىز بۇ مەسىلىنى مەلۇم قىلغان كىشى ئەمەس، ياكى مەلۇمات تەكرارلانغان ياكى "
"ئاللىقاچان تاقالغان.\n"
"\n"
"«apport-bug» نى ئىشلىتىپ يېڭىدىن مەلۇمات تەييارلاڭ."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:496
#: ../apport/ui.py:496
msgid ""
"You are not the reporter of this problem report. It is much easier to mark a "
"bug as a duplicate of another than to move your comments and attachments to "
"a new bug.\n"
"\n"
"Subsequently, we recommend that you file a new bug report using \"apport-"
"bug\" and make a comment in this bug about the one you file.\n"
"\n"
"Do you really want to proceed?"
msgstr ""
"سىز بۇ مەسىلىنى مەلۇم قىلغۇچى ئەمەس. يېڭى كەمتۈك دەپ مەلۇم قىلغاندىن كۆرە، "
"باشقا كەمتۈك بىلەن ئوخشاش دەپ بەلگە قويۇش تېخىمۇ ئاسان.\n"
"\n"
"ئارقىدىن، «apport-bug» نى ئىشلىتىپ، كەمتۈك مەلۇم قىلىپ، مەلۇماتنىڭ ئىچىگە "
"كەمتۈك ھەققىدىكى ئىزاھاتنى يېزىشىڭىزنى تەۋسىيە قىلىمىز.\n"
"\n"
"راستلا داۋاملاشتۇرامسىز؟"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:533
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:550
#: ../apport/ui.py:533 ../apport/ui.py:550
msgid "No additional information collected."
msgstr "قوشۇمچە ئۇچۇرلار توپلانمىدى."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:601
#: ../apport/ui.py:601
msgid "What kind of problem do you want to report?"
msgstr "قانداق مەسىلىنى مەلۇم قىلماقچى؟"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:618
#: ../apport/ui.py:618
msgid "Unknown symptom"
msgstr "نامەلۇم ھادىسە"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:619
#: ../apport/ui.py:619
#, python-format
msgid "The symptom \"%s\" is not known."
msgstr "ھادىسە «%s» نامەلۇم."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:650
#: ../apport/ui.py:650
msgid ""
"After closing this message please click on an application window to report a "
"problem about it."
msgstr ""
"ئۇچۇرنى ياپقاندىن كېيىن پروگرامما كۆزنىكىنى چېكىپ، بۇ مەسىلىنى مەلۇم قىلىڭ."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:660
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:665
#: ../apport/ui.py:660 ../apport/ui.py:665
msgid "xprop failed to determine process ID of the window"
msgstr "xprop كۆزنەكنىڭ ئىجرا ID سىنى تېپىشتا مەغلۇپ بولدى"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:679
#: ../apport/ui.py:679
msgid "%prog <report number>"
msgstr "%prog <مەلۇمات نومۇرى>"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:681
#: ../apport/ui.py:681
msgid "Specify package name."
msgstr "بوغچا ئاتىنى كۆرسىتىپ بېرىڭ."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:683
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:734
#: ../apport/ui.py:683 ../apport/ui.py:734
msgid "Add an extra tag to the report. Can be specified multiple times."
msgstr "دوكلاتقا يېڭىدىن خەتكۈش قوشۇڭ، كۆپ قېتىم بەلگىلەشكە بولىدۇ."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:713
#: ../apport/ui.py:713
msgid ""
"%prog [options] [symptom|pid|package|program path|.apport/.crash file]"
msgstr ""
"%prog [options] [symptom|pid|package|program path|.apport/.crash file]"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:716
#: ../apport/ui.py:716
msgid ""
"Start in bug filing mode. Requires --package and an optional --pid, or just "
"a --pid. If neither is given, display a list of known symptoms. (Implied if "
"a single argument is given.)"
msgstr ""
"كەمتۈك يېزىش ھالىتىدە باشلايدۇ. ئىجرا قىلغاندا --package ۋە --pid ياكى "
"پەقەتلا --pid تاللانمىسىنى يازسىلا بولىدۇ. ئەگەر ھېچقايسى يېزىلمىسا، "
"كۆرۈلگەن ئالامەتلەرنىڭ تىزىمىنى كۆرسىتىدۇ. (پەقەت يالغۇز ئارگۇمېنت "
"بېرىلگەندىلا.)"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:718
#: ../apport/ui.py:718
msgid "Click a window as a target for filing a problem report."
msgstr "خاتالىق دوكلاتىنى تولدۇرۇش ئۈچۈن كۆزنەكنى نىشان قىلىپ چېكىڭ"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:720
#: ../apport/ui.py:720
msgid "Start in bug updating mode. Can take an optional --package."
msgstr ""
"كەمتۈك يېڭىلاش ھالىتىدە قوزغىتىش. --package دېگەن تاللانمىنى ئىشلىتىشكە "
"بولىدۇ."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:722
#: ../apport/ui.py:722
msgid ""
"File a bug report about a symptom. (Implied if symptom name is given as only "
"argument.)"
msgstr ""
"ھادىسە ھەققىدە مەلۇمات تەييارلاڭ. (Implied if symptom name is given as only "
"argument)"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:724
#: ../apport/ui.py:724
msgid ""
"Specify package name in --file-bug mode. This is optional if a --pid is "
"specified. (Implied if package name is given as only argument.)"
msgstr ""
"--file-bug ھالىتىدە بوغچا ئاتىنى كۆرسىتىڭ. ئەگەر --pid كۆرسىتىلگەن بولسا، "
"بۇنى كۆرسەتمىسىمۇ بولىدۇ.(Implied if package name is given as only argument.)"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:726
#: ../apport/ui.py:726
msgid ""
"Specify a running program in --file-bug mode. If this is specified, the bug "
"report will contain more information.  (Implied if pid is given as only "
"argument.)"
msgstr ""
"--file-bug  ھالىتىدە ئىجرا بولۇۋاتقان پروگراممىنى كۆرسىتىڭ. ئەگەر بۇ "
"كۆرسىتىلسە، كەمتۈك مەلۇماتىغا تېخىمۇ كۆپ ئۇچۇرلار قوشۇلىدۇ. (Implied if pid "
"is given as only argument.)"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:728
#: ../apport/ui.py:728
msgid "The provided pid is a hanging application."
msgstr ""
"تەمىنلەنگەن pid بولسا بىر ئېسىلىپ قالغان(توختاپ قالغان) پروگرامما ئىكەن."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:730
#: ../apport/ui.py:730
#, python-format
msgid ""
"Report the crash from given .apport or .crash file instead of the pending "
"ones in %s. (Implied if file is given as only argument.)"
msgstr ""
"چاتاق مەلۇماتىنى  %s نىڭدىكى كۈتۈپ تۇرغان ھۆججەتنى ئەمەس بەلكى بېرىلگەن  "
".apport ياكى .crash ھۆججىتىنى ئىشلىتىپ يوللاش(پەقەت ھۆججەت ئاتى ئارگۇمېنت "
"شەكىلدە بېرىلگەندىلا.)"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:732
#: ../apport/ui.py:732
msgid ""
"In bug filing mode, save the collected information into a file instead of "
"reporting it. This file can then be reported later on from a different "
"machine."
msgstr ""
"كەمتۈك يېزىش ھالىتىدە، توپلانغان ئۇچۇرلارنى مەلۇم قىلماي ھۆججەتكە ساقلاپ "
"قويۇشقا، بۇ ھۆججەتنى كېيىن باشقا كومپيۇتېر ئارقىلىق يوللاشقىمۇ بولىدۇ."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:736
#: ../apport/ui.py:736
msgid "Print the Apport version number."
msgstr "Apport نىڭ نەشر نومۇرىنى بېسىپ چىقىرىدۇ."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:870
#: ../apport/ui.py:870
msgid ""
"This will launch apport-retrace in a terminal window to examine the crash."
msgstr ""
"crash نى تەكشۈرۈش ئۈچۈن apport-retrace تېرمىنال كۆزنىكىدە ئىجرا بولىدۇ."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:871
#: ../apport/ui.py:871
msgid "Run gdb session"
msgstr "gdb ئەڭگىمەسىنى ئىجرا قىلىش"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:872
#: ../apport/ui.py:872
msgid "Run gdb session without downloading debug symbols"
msgstr "سازلاش بەلگىلىرىنى چۈشۈرمەيلا gdb ئەڭگىمەسىنى ئىجرا قىلىش"

#. TRANSLATORS: %s contains the crash report file name
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:874
#: ../apport/ui.py:874
#, python-format
msgid "Update %s with fully symbolic stack trace"
msgstr "%s نى تولۇق بەلگىلەر بىلەن يېڭىلاش"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:947
#: ../apport/ui.py:947
#, python-format
msgid ""
"The problem happened with the program %s which changed since the crash "
"occurred."
msgstr "توقۇنۇشتا ئۆزگەرگەن پروگرامما %s تە خاتالىق كۆرۈلدى."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1051
#: ../apport/ui.py:1051
msgid "Could not determine the package or source package name."
msgstr "بوغچا ياكى مەنبە كود بوغچىسىنىڭ نامىنى بېكىتكىلى بولمىدى."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1069
#: ../apport/ui.py:1069
msgid "Unable to start web browser"
msgstr "توركۆرگۈنى قوزغاتقىلى بولمىدى"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1070
#: ../apport/ui.py:1070
#, python-format
msgid "Unable to start web browser to open %s."
msgstr "%s نى كۆرىدىغان توركۆرگۈنى قوزغاتقىلى بولمىدى."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1145
#: ../apport/ui.py:1145
#, python-format
msgid "Please enter your account information for the %s bug tracking system"
msgstr "كەمتۈك باشقۇرۇش سىستېمىسى %s غا ھېسابات ئۇچۇرىڭىزنى كىرگۈزۈڭ."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1157
#: ../apport/ui.py:1157
msgid "Network problem"
msgstr "توردىكى مەسىلە"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1159
#: ../apport/ui.py:1159
msgid ""
"Cannot connect to crash database, please check your Internet connection."
msgstr "crash ساندىنىغا باغلىنالمىدى، ئىنتېرنېت باغلىنىشىنى تەكشۈرۈپ كۆرۈڭ."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1186
#: ../apport/ui.py:1186
msgid "Memory exhaustion"
msgstr "ئەسلەك يېتىشمىدى"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1187
#: ../apport/ui.py:1187
msgid "Your system does not have enough memory to process this crash report."
msgstr ""
"سىستېمىڭىزدا مەزكۇر crash مەلۇماتىنى بىر تەرەپ قىلىشقا يېتەرلىك ئەسلەك يوق."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1210
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1219
#: ../apport/ui.py:1210 ../apport/ui.py:1219
msgid ""
"This problem report applies to a program which is not installed any more."
msgstr "بۇ دوكلات زادىلا ئورنىتىلىپ باقمىغان پروگراممىغا ئىشلىتىلىدۇ."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1240
#: ../apport/ui.py:1240
#, python-format
msgid ""
"The problem cannot be reported:\n"
"\n"
"%s"
msgstr ""
"مەسىلىنى مەلۇم قىلغىلى بولمىدى:\n"
"\n"
"%s"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1291
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1298
#: ../apport/ui.py:1291 ../apport/ui.py:1298
msgid "Problem already known"
msgstr "مەسىلە ئاللىقاچان ئايدىڭلاشقان"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1292
#: ../apport/ui.py:1292
msgid ""
"This problem was already reported in the bug report displayed in the web "
"browser. Please check if you can add any further information that might be "
"helpful for the developers."
msgstr ""
"توركۆرگۈدىكى كەمتۈك دوكلاتىدا بۇ مەسىلە ئاللىقاچان مەلۇم قىلىنغان. تەكشۈرۈپ "
"كۆرۈڭ، ئەگەر سىزنىڭ مەلۇماتىڭىزدا تېخىمۇ كۆپرەك ئۇچۇرلار بار بولسا "
"ئىجادىيەتچىلەر ئۈچۈن تېخىمۇ پايدىلىق بولاتتى."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1299
#: ../apport/ui.py:1299
msgid "This problem was already reported to developers. Thank you!"
msgstr "مەسىلە ئىجادىيەتچىلەرگە مەلۇم قىلىندى. سىزگە تەشەككۈر!"

#: ../bin/apport-cli.py:73 ../debian/tmp/usr/bin/apport-cli.py:73
msgid "Press any key to continue..."
msgstr "خالىغان كۇنۇپكىنى باسسىڭىز داۋاملىشىدۇ..."

#: ../bin/apport-cli.py:80 ../debian/tmp/usr/bin/apport-cli.py:80
msgid "What would you like to do? Your options are:"
msgstr "نېمە قىلغۇڭىز بار؟ سىز تۆۋەندىكىلەرنى قىلالايسىز:"

#: ../bin/apport-cli.py:84 ../debian/tmp/usr/bin/apport-cli.py:84
#, python-format
msgid "Please choose (%s):"
msgstr "تاللاڭ(%s):"

#: ../bin/apport-cli.py:144 ../debian/tmp/usr/bin/apport-cli.py:144
#, python-format
msgid "(%i bytes)"
msgstr "(%i بايت)"

#: ../debian/tmp/usr/share/apport/apport-kde.py:335 ../gtk/apport-gtk.py:138
#: ../bin/apport-cli.py:146 ../debian/tmp/usr/share/apport/apport-gtk.py:138
#: ../kde/apport-kde.py:335 ../debian/tmp/usr/bin/apport-cli.py:146
msgid "(binary data)"
msgstr "(ئىككىلىك سانلىق-مەلۇمات)"

#: ../debian/tmp/usr/share/apport/apport-kde.py:162
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:395
#: ../gtk/apport-gtk.py:173
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:273
#: ../bin/apport-cli.py:174 ../debian/tmp/usr/share/apport/apport-gtk.py:173
#: ../kde/apport-kde.py:162 ../debian/tmp/usr/bin/apport-cli.py:174
msgid "Send problem report to the developers?"
msgstr "بۇ مەلۇماتنى ئىجادىيەتچىگە ئەۋەتسۇنمۇ؟"

#: ../bin/apport-cli.py:175 ../debian/tmp/usr/bin/apport-cli.py:175
msgid ""
"After the problem report has been sent, please fill out the form in the\n"
"automatically opened web browser."
msgstr ""
"مەلۇماتنى ئەۋەتىپ بولغاندىن كېيىن \n"
"توركۆرگۈدە ئېچىلغان بەتتىكى جەدۋەلنى تولدۇرۇڭ."

#: ../bin/apport-cli.py:178 ../debian/tmp/usr/bin/apport-cli.py:178
#, python-format
msgid "&Send report (%s)"
msgstr "مەلۇمات (%s) نى ئەۋەت(&S)"

#: ../bin/apport-cli.py:182 ../debian/tmp/usr/bin/apport-cli.py:182
msgid "&Examine locally"
msgstr "يەرلىكتە تەكشۈر(&E)"

#: ../bin/apport-cli.py:186 ../debian/tmp/usr/bin/apport-cli.py:186
msgid "&View report"
msgstr "مەلۇمات كۆرسەت(&V)"

#: ../bin/apport-cli.py:187 ../debian/tmp/usr/bin/apport-cli.py:187
msgid "&Keep report file for sending later or copying to somewhere else"
msgstr ""
"كېيىن يەنە باشقىلارغا ئەۋەتىش ياكى كۆچۈرۈپ بېرىش ئۈچۈن مەلۇمات ھۆججىتى "
"ساقلاپ قوي(&K)"

#: ../bin/apport-cli.py:188 ../debian/tmp/usr/bin/apport-cli.py:188
msgid "Cancel and &ignore future crashes of this program version"
msgstr ""
"پروگراممىنىڭ مەزكۇر نەشرىدە بۇنىڭدىن كېلىپ چىققان crashes نى ئەمەلدىن قالدۇر "
"ياكى پىسەنت قىلما(&I)"

#: ../bin/apport-cli.py:190 ../bin/apport-cli.py:267 ../bin/apport-cli.py:299
#: ../bin/apport-cli.py:320 ../debian/tmp/usr/bin/apport-cli.py:190
#: ../debian/tmp/usr/bin/apport-cli.py:267
#: ../debian/tmp/usr/bin/apport-cli.py:299
#: ../debian/tmp/usr/bin/apport-cli.py:320
msgid "&Cancel"
msgstr "ئەمەلدىن قالدۇر(&C)"

#: ../bin/apport-cli.py:218 ../debian/tmp/usr/bin/apport-cli.py:218
msgid "Problem report file:"
msgstr "مەلۇمات ھۆججىتى:"

#: ../bin/apport-cli.py:224 ../bin/apport-cli.py:229
#: ../debian/tmp/usr/bin/apport-cli.py:224
#: ../debian/tmp/usr/bin/apport-cli.py:229
msgid "&Confirm"
msgstr "جەزملە(&C)"

#: ../bin/apport-cli.py:228 ../debian/tmp/usr/bin/apport-cli.py:228
#, python-format
msgid "Error: %s"
msgstr "خاتالىق: %s"

#: ../debian/tmp/usr/share/apport/apport-kde.py:380 ../bin/apport-cli.py:234
#: ../kde/apport-kde.py:380 ../debian/tmp/usr/bin/apport-cli.py:234
msgid "Collecting problem information"
msgstr "مەسىلىلەرگە ئائىت ئۇچۇرلارنى توپلاۋاتىدۇ"

#: ../bin/apport-cli.py:235 ../debian/tmp/usr/bin/apport-cli.py:235
msgid ""
"The collected information can be sent to the developers to improve the\n"
"application. This might take a few minutes."
msgstr ""
"ئىجادىيەتچىلەرنىڭ پروگراممىنى مۇكەممەللەشتۈرۈشى ئۈچۈن \n"
"توپلانغان ئۇچۇرلارنى ئەۋەتىدۇ. بۇنىڭغا ئازراق ۋاقىت كېتىدۇ."

#: ../debian/tmp/usr/share/apport/apport-kde.py:408 ../gtk/apport-gtk.ui.h:13
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:13 ../bin/apport-cli.py:247
#: ../kde/apport-kde.py:408 ../debian/tmp/usr/bin/apport-cli.py:247
msgid "Uploading problem information"
msgstr "مەسىلىلەر ھەققىدىكى ئۇچۇرلارنى يېڭىلاۋاتىدۇ"

#: ../bin/apport-cli.py:248 ../debian/tmp/usr/bin/apport-cli.py:248
msgid ""
"The collected information is being sent to the bug tracking system.\n"
"This might take a few minutes."
msgstr ""
"توپلانغان ئۇچۇرلارنى كەمتۈك باشقۇرۇش سىستېمىسىغا ئەۋەتىدۇ.\n"
"بۇنىڭغا ئازراق ۋاقىت كېتىدۇ."

#: ../bin/apport-cli.py:298 ../debian/tmp/usr/bin/apport-cli.py:298
msgid "&Done"
msgstr "تامام(&D)"

#: ../bin/apport-cli.py:304 ../debian/tmp/usr/bin/apport-cli.py:304
msgid "none"
msgstr "يوق"

#: ../bin/apport-cli.py:305 ../debian/tmp/usr/bin/apport-cli.py:305
#, python-format
msgid "Selected: %s. Multiple choices:"
msgstr "تاللانغىنى : %s. كوپنى تاللاش:"

#: ../bin/apport-cli.py:321 ../debian/tmp/usr/bin/apport-cli.py:321
msgid "Choices:"
msgstr "تاللاشلار:"

#: ../bin/apport-cli.py:335 ../debian/tmp/usr/bin/apport-cli.py:335
msgid "Path to file (Enter to cancel):"
msgstr "ھۆججەتنىڭ يولى(بولدى قىلىش ئۈچۈن قايتۇرۇش كۇنۇپكىسىنى بېسىڭ):"

#: ../bin/apport-cli.py:341 ../debian/tmp/usr/bin/apport-cli.py:341
msgid "File does not exist."
msgstr "ھۆججەت مەۋجۇت ئەمەس."

#: ../bin/apport-cli.py:343 ../debian/tmp/usr/bin/apport-cli.py:343
msgid "This is a directory."
msgstr "بۇ بىر مۇندەرىجە."

#: ../bin/apport-cli.py:349 ../debian/tmp/usr/bin/apport-cli.py:349
msgid "To continue, you must visit the following URL:"
msgstr "داۋاملاشتۇرۇش ئۈچۈن تۆۋەندىكى URL نى كۆرۈشىڭىز كېرەك:"

#: ../bin/apport-cli.py:351 ../debian/tmp/usr/bin/apport-cli.py:351
msgid ""
"You can launch a browser now, or copy this URL into a browser on another "
"computer."
msgstr ""
"ئەمدى توركۆرگۈنى قوزغىتىڭ ياكى، URL نى باشقا كومپيۇتېردىكى توركۆرگۈگە "
"كۆچۈرۈڭ."

#: ../bin/apport-cli.py:353 ../debian/tmp/usr/bin/apport-cli.py:353
msgid "Launch a browser now"
msgstr "ھازىرلا توركۆرگۈنى قوزغىتىش"

#: ../bin/apport-cli.py:367 ../debian/tmp/usr/bin/apport-cli.py:367
msgid "No pending crash reports. Try --help for more information."
msgstr ""
"تېخى بىر تەرەپ قىلىنمىغان crash ھەققىدىكى مەلۇمات يوق. --help نى ئىشلەتسىڭىز "
"تېخىمۇ كوپ ئۇچۇرغا ئېرىشەلەيسىز."

#: ../debian/tmp/usr/share/apport/apportcheckresume.py:67
#: ../data/apportcheckresume.py:67
msgid ""
"This occured during a previous suspend and prevented it from resuming "
"properly."
msgstr ""
"بۇ ئالدىنقى قېتىملىق توڭلىتىش جەريانىدا يۈز بەرگەن بولۇپ، قايتا باشلاشقا "
"بولمىدى."

#: ../debian/tmp/usr/share/apport/apportcheckresume.py:69
#: ../data/apportcheckresume.py:69
msgid ""
"This occured during a previous hibernate and prevented it from resuming "
"properly."
msgstr ""
"بۇ ئالدىنقى قېتىملىق ئۈچەككە كىرگۈزۈش جەريانىدا يۈز بەرگەن بولۇپ، قايتا "
"باشلاشقا بولمىدى."

#: ../debian/tmp/usr/share/apport/apportcheckresume.py:74
#: ../data/apportcheckresume.py:74
msgid ""
"The resume processing hung very near the end and will have appeared to have "
"completed normally."
msgstr ""
"ئەسلىگە قايتۇرۇش باسقۇچى ئاخىرلىشاي دەپ قالدى، بۇنداق بولغاندا نورمال "
"تاماملىنىدۇ."

#: ../bin/apport-retrace.py:40 ../debian/tmp/usr/bin/apport-retrace.py:40
msgid "%prog [options] <apport problem report | crash ID>"
msgstr "%prog [options] <apport problem report | crash ID>"

#: ../bin/apport-retrace.py:42 ../debian/tmp/usr/bin/apport-retrace.py:42
msgid "Do not put the new traces into the report, but write them to stdout."
msgstr "بۇ يېڭى چىققانلىرىنى مەلۇماتقا يازماي stdout قا يازسۇن."

#: ../bin/apport-retrace.py:44 ../debian/tmp/usr/bin/apport-retrace.py:44
msgid ""
"Start an interactive gdb session with the report's core dump (-o ignored; "
"does not rewrite report)"
msgstr ""
"مەلۇماتنىڭ غول تۆكمىسىگە نىسبەتەن تەسىرلىشىشچان gdb ئەڭگىمەسىنى باشلايدۇ(-o "
"غا پەرۋا قىلمايدۇ؛ مەلۇماتنى قاپلىمايدۇ)"

#: ../bin/apport-retrace.py:46 ../debian/tmp/usr/bin/apport-retrace.py:46
msgid ""
"Write modified report to given file instead of changing the original report"
msgstr "ئەسلىدىكى مەلۇماتقا يازماي كۆرسىتىلگەن ھۆججەتكە يازسۇن."

#: ../bin/apport-retrace.py:48 ../debian/tmp/usr/bin/apport-retrace.py:48
msgid "Remove the core dump from the report after stack trace regeneration"
msgstr ""
"stack ئىزلىشى قايتا ھاسىللانغاندىن كېيىن، غول تۆكمىنى(core dump) مەلۇماتتىن "
"چىقىرىۋېتىش"

#: ../bin/apport-retrace.py:50 ../debian/tmp/usr/bin/apport-retrace.py:50
msgid "Override report's CoreFile"
msgstr "دوكلاتنىڭ CoreFile نى قاپلاش"

#: ../bin/apport-retrace.py:52 ../debian/tmp/usr/bin/apport-retrace.py:52
msgid "Override report's ExecutablePath"
msgstr "دوكلاتنىڭ ExecutablePath نى قاپلاش"

#: ../bin/apport-retrace.py:54 ../debian/tmp/usr/bin/apport-retrace.py:54
msgid "Override report's ProcMaps"
msgstr "دوكلاتنىڭ ProcMaps نى قاپلاش"

#: ../bin/apport-retrace.py:56 ../debian/tmp/usr/bin/apport-retrace.py:56
msgid "Rebuild report's Package information"
msgstr "دوكلاتنىڭ بوغچا ئۇچۇرىنى قايتا قۇرۇش"

#: ../bin/apport-retrace.py:58 ../debian/tmp/usr/bin/apport-retrace.py:58
msgid ""
"Build a temporary sandbox and download/install the necessary packages and "
"debug symbols in there; without this option it assumes that the necessary "
"packages and debug symbols are already installed in the system. The argument "
"points to the packaging system configuration base directory; if you specify "
"\"system\", it will use the system configuration files, but will then only "
"be able to retrace crashes that happened on the currently running release."
msgstr ""
"ۋاقتىنچە قۇم ساندۇقى قۇرىدۇ ھەم قاچىلاش بوغچىسىنى يۈكلەيدۇ/قاچىلايدۇ.ئەگەر "
"بۇ تاللانما ئىشلىتىلمىسە، سىستېمىغا لازىملىق دېتالنى قاچىلايدۇ. ئەگەر سىز "
"سىستېما بەلگىلىمىسىڭىز، سىستېما سەپلىمىسىنى ئىشلىتىدۇ، شۇنىڭ بىلەن ئىجرا "
"قىلىنىۋاتقان سىستېمىنى ھالاك قىلىدۇ."

#: ../bin/apport-retrace.py:60 ../debian/tmp/usr/bin/apport-retrace.py:60
msgid ""
"Report download/install progress when installing packages into sandbox"
msgstr ""
"بوغچىلارنى قۇم خالتىسى ئىچىگە ئورناتقاندىكى چۈشۈرۈش/ئورنىتىش جەريانىنى مەلۇم "
"قىلىش"

#: ../bin/apport-retrace.py:62 ../debian/tmp/usr/bin/apport-retrace.py:62
msgid "Prepend timestamps to log messages, for batch operation"
msgstr ""
"ئۇچۇر خاتىرىلەشتىن بۇرۇن ۋاقىتنى خاتىرىلەڭ، بۇ قېتىملىق مەشغۇلاتنى "
"تەمىنلەيدۇ."

#: ../bin/apport-retrace.py:64 ../debian/tmp/usr/bin/apport-retrace.py:64
msgid "Cache directory for packages downloaded in the sandbox"
msgstr "قۇم خالتىسى ئىچىگە چۈشۈرۈلگەن بوغچىلارنىڭ غەملەك مۇندەرىجىسى"

#: ../bin/apport-retrace.py:66 ../debian/tmp/usr/bin/apport-retrace.py:66
msgid ""
"Directory for unpacked packages. Future runs will assume that any already "
"downloaded package is also extracted to this sandbox."
msgstr ""
"يېيىلمىغان بوغچىلارنىڭ مۇندەرىجىسى. كېيىن ئىجرا قىلىدىغان چاغدا، چۈشۈرۈلگەن "
"بوغچىلار مۇشۇ يەرگە يېيىلىدۇ."

#: ../bin/apport-retrace.py:68 ../debian/tmp/usr/bin/apport-retrace.py:68
msgid ""
"Install an extra package into the sandbox (can be specified multiple times)"
msgstr ""
"قۇم خالتىسى ئىچىگە قوشۇمچە بوغچىنى ئورنىتىش(بىر قانچە قېتىم كۆرسىتىشكە "
"بولىدۇ)"

#: ../bin/apport-retrace.py:70 ../debian/tmp/usr/bin/apport-retrace.py:70
msgid ""
"Path to a file with the crash database authentication information. This is "
"used when specifying a crash ID to upload the retraced stack traces (only if "
"neither -g, -o, nor -s are specified)"
msgstr ""
"يىمىرىلىش ساندانىنى زىيارەت قىلىش ئۇچۇرى ھۆججىتىنىڭ يولىنى ئۆز ئىچىگە "
"ئالىدۇ. بۇ تاللانما مۇئەييەن يىمىرىلىش كودىدا  ئىزلاشنىڭ قايتۇرما سازلاش "
"ئۇچۇرى ئۈچۈن ئىشلىتىلىدۇ. (ئىشلەتكۈچى -g, -o, ياكى -s نى بەلگىلىگەن "
"بولمىسىلا)"

#: ../bin/apport-retrace.py:72 ../debian/tmp/usr/bin/apport-retrace.py:72
msgid ""
"Display retraced stack traces and ask for confirmation before sending them "
"to the crash database."
msgstr ""
"قايتۇرغان ئىزلاش ئۇچۇرىنى كۆرسىتىدۇ ھەمدە يىمىرىلىش ساندىنىغا يوللاش "
"يوللىماسلىقنى جەزملەشنى سورايدۇ."

#: ../bin/apport-retrace.py:74 ../debian/tmp/usr/bin/apport-retrace.py:74
msgid ""
"Path to the duplicate sqlite database (default: no duplicate checking)"
msgstr ""
"تەكرارلانغان sqlite ساندىنىنىڭ يولى.(كۆڭۈلدە تەكرارلىنىشنى تەكشۈرمەيدۇ)"

#: ../bin/apport-retrace.py:79 ../debian/tmp/usr/bin/apport-retrace.py:79
msgid "incorrect number of arguments; use --help for a short help"
msgstr ""
"argument لارنىڭ سانى توغرا ئەمەس. --help نى ئىشلىتىپ قىسقىچە چۈشەندۈرۈشىنى "
"كۆرۈڭ."

#: ../bin/apport-retrace.py:83 ../debian/tmp/usr/bin/apport-retrace.py:83
msgid ""
"you either need to do a local operation (-s, -g, -o) or supply an "
"authentication file (--auth); see --help for a short help"
msgstr ""
"يەرلىكتە مەشغۇلات قىلىشىڭىز (-s، -g، -o) ياكى سالاھىيەت دەلىللەش ھۆججىتىنى (-"
"-auth) تەمىنلىشىڭىز كېرەك. ئاددىي ياردەم ئۇچۇرىغا ئېرىشىش ئۈچۈن --help نى "
"ئىشلىتىڭ."

#. translators: don't translate y/n, apport currently only checks for "y"
#: ../bin/apport-retrace.py:117 ../debian/tmp/usr/bin/apport-retrace.py:117
msgid "OK to send these as attachments? [y/n]"
msgstr "بۇ قوشۇلما ھۆججەتلەرنى ئەۋەتسە بولامدۇ؟[y/n]"

#: ../gtk/apport-gtk-mime.desktop.in.h:1 ../kde/apport-kde-mime.desktop.in.h:1
#: ../kde/apport-kde.desktop.in.h:1 ../gtk/apport-gtk.desktop.in.h:1
msgid "Report a problem..."
msgstr "مەسىلىنى مەلۇم قىلىش..."

#: ../gtk/apport-gtk-mime.desktop.in.h:2 ../kde/apport-kde-mime.desktop.in.h:2
#: ../kde/apport-kde.desktop.in.h:2 ../gtk/apport-gtk.desktop.in.h:2
msgid "Report a malfunction to the developers"
msgstr "خاتالىقنى ئىجادىيەتچىگە مەلۇم قىلىدۇ"

#: ../debian/tmp/usr/share/apport/kernel_oops.py:28 ../data/kernel_oops.py:28
msgid "Your system might become unstable now and might need to be restarted."
msgstr ""
"سىستېمىڭىزنىڭ تۇراقسىز بولۇپ قېلىش ئېھتىماللىقى بار، قايتا قوزغىتىش "
"زۆرۈرىيىتى باردەك قىلىدۇ."

#: ../gtk/apport-gtk.py:153 ../debian/tmp/usr/share/apport/apport-gtk.py:153
#, python-format
msgid "Sorry, the application %s has stopped unexpectedly."
msgstr "كەچۈرۈڭ، پروگرامما %s  تاسادىپىي توختاپ قالدى."

#: ../gtk/apport-gtk.py:156 ../debian/tmp/usr/share/apport/apport-gtk.py:156
#, python-format
msgid "Sorry, %s has closed unexpectedly."
msgstr "كەچۈرۈڭ، %s تاسادىپىي تاقالدى."

#: ../debian/tmp/usr/share/apport/apport-kde.py:176
#: ../debian/tmp/usr/share/apport/apport-kde.py:214
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:108
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:291
#: ../gtk/apport-gtk.py:161
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:106
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:241
#: ../debian/tmp/usr/share/apport/apport-gtk.py:161 ../kde/apport-kde.py:176
#: ../kde/apport-kde.py:214
#, python-format
msgid "Sorry, %s has experienced an internal error."
msgstr "كەچۈرۈڭ، %s ئىچكى خاتالىققا يولۇقتى."

#: ../debian/tmp/usr/share/apport/apport-kde.py:170
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:403
#: ../gtk/apport-gtk.py:182
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:279
#: ../debian/tmp/usr/share/apport/apport-gtk.py:182 ../kde/apport-kde.py:170
msgid "Send"
msgstr "يوللا"

#: ../debian/tmp/usr/share/apport/apport-kde.py:268 ../gtk/apport-gtk.ui.h:7
#: ../gtk/apport-gtk.py:200 ../gtk/apport-gtk.py:567
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:7
#: ../debian/tmp/usr/share/apport/apport-gtk.py:200
#: ../debian/tmp/usr/share/apport/apport-gtk.py:567 ../kde/apport-kde.py:268
msgid "Show Details"
msgstr "تەپسىلاتلارنى كۆرسەت"

#: ../debian/tmp/usr/share/apport/apport-kde.py:211
#: ../debian/tmp/usr/share/apport/apport-kde.py:220
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:115
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:144
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:183
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:301
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:341
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:445
#: ../gtk/apport-gtk.ui.h:10 ../gtk/apport-gtk.py:212 ../gtk/apport-gtk.py:282
#: ../gtk/apport-gtk.py:297 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:10
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:111
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:137
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:173
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:249
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:319
#: ../debian/tmp/usr/share/apport/apport-gtk.py:212
#: ../debian/tmp/usr/share/apport/apport-gtk.py:282
#: ../debian/tmp/usr/share/apport/apport-gtk.py:297 ../kde/apport-kde.py:211
#: ../kde/apport-kde.py:220
msgid "Continue"
msgstr "داۋاملاشتۇر"

#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:267
#: ../gtk/apport-gtk.py:224 ../debian/tmp/usr/share/apport/apport-gtk.py:224
msgid "Force Closed"
msgstr "مەجبۇرىي يېپىلغان"

#: ../debian/tmp/usr/share/apport/apport-kde.py:208
#: ../debian/tmp/usr/share/apport/apport-kde.py:354
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:223
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:264
#: ../gtk/apport-gtk.py:225 ../gtk/apport-gtk.py:279
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:213
#: ../debian/tmp/usr/share/apport/apport-gtk.py:225
#: ../debian/tmp/usr/share/apport/apport-gtk.py:279 ../kde/apport-kde.py:208
#: ../kde/apport-kde.py:354
msgid "Relaunch"
msgstr "قايتا ئىجرا قىل"

#: ../gtk/apport-gtk.py:234 ../debian/tmp/usr/share/apport/apport-gtk.py:234
#, python-format
msgid "The application %s has stopped responding."
msgstr "پروگرامما %s جاۋاب قايتۇرۇشتىن توختىدى."

#: ../gtk/apport-gtk.py:238 ../debian/tmp/usr/share/apport/apport-gtk.py:238
#, python-format
msgid "The program \"%s\" has stopped responding."
msgstr "پروگرامما «%s» جاۋاب قايتۇرۇشتىن توختىدى."

#: ../debian/tmp/usr/share/apport/apport-kde.py:184 ../gtk/apport-gtk.py:253
#: ../debian/tmp/usr/share/apport/apport-gtk.py:253 ../kde/apport-kde.py:184
#, python-format
msgid "Package: %s"
msgstr "بوغچا: %s"

#: ../debian/tmp/usr/share/apport/apport-kde.py:190
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:137
#: ../gtk/apport-gtk.py:260
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:132
#: ../debian/tmp/usr/share/apport/apport-gtk.py:260 ../kde/apport-kde.py:190
msgid "Sorry, a problem occurred while installing software."
msgstr "كەچۈرۈڭ، يۇمشاق دېتال ئورناتقاندا بىر خاتالىق كۆرۈلدى."

#: ../debian/tmp/usr/share/apport/apport-kde.py:197 ../gtk/apport-gtk.py:269
#: ../gtk/apport-gtk.py:286 ../debian/tmp/usr/share/apport/apport-gtk.py:269
#: ../debian/tmp/usr/share/apport/apport-gtk.py:286 ../kde/apport-kde.py:197
#, python-format
msgid "The application %s has experienced an internal error."
msgstr "پروگرامما %s نىڭدا بىر ئىچكى خاتالىق يۈز بەردى."

#: ../debian/tmp/usr/share/apport/apport-kde.py:201 ../gtk/apport-gtk.py:272
#: ../debian/tmp/usr/share/apport/apport-gtk.py:272 ../kde/apport-kde.py:201
#, python-format
msgid "The application %s has closed unexpectedly."
msgstr "بۇ %s ئەپ تاسادىپىي تاقالدى."

#: ../debian/tmp/usr/share/apport/apport-kde.py:207 ../gtk/apport-gtk.ui.h:9
#: ../gtk/apport-gtk.py:278 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:9
#: ../debian/tmp/usr/share/apport/apport-gtk.py:278 ../kde/apport-kde.py:207
msgid "Leave Closed"
msgstr "تاقاق پېتى قالدۇر"

#: ../debian/tmp/usr/share/apport/apport-kde.py:217
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:293
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:333
#: ../gtk/apport-gtk.ui.h:4 ../gtk/apport-gtk.py:294
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:4
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:243
#: ../debian/tmp/usr/share/apport/apport-gtk.py:294 ../kde/apport-kde.py:217
msgid "If you notice further problems, try restarting the computer."
msgstr ""
"ئەگەر تېخىمۇ كۆپ مەسىلىنى بايقىسىڭىز، كومپيۇتېرنى قايتا قوزغىتىشنى سىناڭ."

#: ../debian/tmp/usr/share/apport/apport-kde.py:221 ../gtk/apport-gtk.py:298
#: ../debian/tmp/usr/share/apport/apport-gtk.py:298 ../kde/apport-kde.py:221
msgid "Ignore future problems of this type"
msgstr "بۇ تۈردىكى كەلگۈسىدىكى مەسىلىگە سەل قاراش"

#: ../debian/tmp/usr/share/apport/apport-kde.py:265 ../gtk/apport-gtk.py:571
#: ../debian/tmp/usr/share/apport/apport-gtk.py:571 ../kde/apport-kde.py:265
msgid "Hide Details"
msgstr "تەپسىلاتلارنى يوشۇر"

#: ../debian/tmp/usr/share/apport/apport-kde.py:291 ../kde/apport-kde.py:291
msgid "Username:"
msgstr "ئىشلەتكۈچى ئاتى:"

#: ../debian/tmp/usr/share/apport/apport-kde.py:292 ../kde/apport-kde.py:292
msgid "Password:"
msgstr "ئىم:"

#: ../debian/tmp/usr/share/apport/apport-kde.py:379 ../kde/apport-kde.py:379
msgid "Collecting Problem Information"
msgstr "چاتاق ھەققىدىكى ئۇچۇرلارنى توپلاۋاتىدۇ"

#: ../debian/tmp/usr/share/apport/apport-kde.py:381 ../kde/apport-kde.py:381
msgid ""
"The collected information can be sent to the developers to improve the "
"application. This might take a few minutes."
msgstr ""
"ئىجادىيەتچىنىڭ پروگرامما ئىقتىدارىنى ياخشىلىشىغا قۇلايلىق يارىتىش ئۈچۈن، "
"توپلانغان ئۇچۇرلار ئىجادىيەتچىگە يوللىنىدۇ. بۇنىڭغا بىرقانچە مىنۇت كېتىدۇ."

#: ../debian/tmp/usr/share/apport/apport-kde.py:407 ../kde/apport-kde.py:407
msgid "Uploading Problem Information"
msgstr "چاتاق ھەققىدىكى ئۇچۇرلارنى يۈكلەۋاتىدۇ"

#: ../debian/tmp/usr/share/apport/apport-kde.py:409 ../gtk/apport-gtk.ui.h:15
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:15 ../kde/apport-kde.py:409
msgid ""
"The collected information is being sent to the bug tracking system. This "
"might take a few minutes."
msgstr ""
"توپلانغان ئۇچۇرلارنى كەمتۈك باشقۇرۇش سىستېمىسىغا ئەۋەتمەكچى. بۇنىڭغا ئازراق "
"ۋاقىت كېتىدۇ."

#: ../debian/tmp/usr/share/apport/apport-kde.py:443
#: ../debian/tmp/usr/share/apport/apport-kde.py:479 ../gtk/apport-gtk.ui.h:1
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:1 ../kde/apport-kde.py:443
#: ../kde/apport-kde.py:479
msgid "Apport"
msgstr "Apport"

#: ../apport/com.ubuntu.apport.policy.in.h:1
msgid "Collect system information"
msgstr "سىستېما ئۇچۇرلىرىنى توپلا"

#: ../apport/com.ubuntu.apport.policy.in.h:2
msgid ""
"Authentication is required to collect system information for this problem "
"report"
msgstr ""
"بۇ مەسىلىنى مەلۇم قىلىشتا سىستېما ئۇچۇرلىرىنى توپلاش كېرەك، بىراق بۇنىڭ "
"ئۈچۈن كىملىك دەلىللەش زۆرۈردۇر."

#: ../gtk/apport-gtk.ui.h:2 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:2
msgid "Crash report"
msgstr "يىمىرىلىش دوكلاتى"

#: ../gtk/apport-gtk.ui.h:3 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:3
msgid "<big><b>Sorry, an internal error happened.</b></big>"
msgstr "<big><b>كەچۈرۈڭ، ئىچكى خاتالىق يۈز بەردى.</b></big>"

#: ../gtk/apport-gtk.ui.h:5 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:5
msgid "Send an error report to help fix this problem"
msgstr ""
"بۇ مەسىلىنى ئوڭلاشقا ياردەم قىلىش ئۈچۈن خاتالىق دوكلاتىدىن بىرنى يوللاڭ"

#: ../gtk/apport-gtk.ui.h:6 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:6
msgid "Ignore future problems of this program version"
msgstr "بۇ پروگرامما نەشرىنىڭ كەلگۈسىدىكى مەسىلىلىرىگە پەرۋا قىلما"

#: ../gtk/apport-gtk.ui.h:8 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:8
msgid "_Examine locally"
msgstr "يەرلىكتە تەكشۈر(_E)"

#: ../gtk/apport-gtk.ui.h:11 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:11
msgid "<big><b>Collecting problem information</b></big>"
msgstr "<big><b>مەسىلە ھەققىدە ئۇچۇرلارنى توپلاۋاتىدۇ</b></big>"

#: ../gtk/apport-gtk.ui.h:12 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:12
msgid ""
"Information is being collected that may help the developers fix the problem "
"you report."
msgstr ""
"سىز مەلۇم قىلغان مەسىلىنى ئىجادىيەتچىلەرنىڭ تۈزىتىشىگە ياردىمى بولسۇن دەپ "
"ئۇچۇرلار توپلاندى."

#: ../gtk/apport-gtk.ui.h:14 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:14
msgid "<big><b>Uploading problem information</b></big>"
msgstr "<big><b>مەسىلە ھەققىدىكى ئۇچۇرلارنى يۈكلەۋاتىدۇ</b></big>"

#: ../kde/apport-kde-mimelnk.desktop.in.h:1
msgid "Apport crash file"
msgstr "Apport چاتاق ھۆججىتى"

#: ../debian/tmp/usr/bin/apport-unpack.py:22 ../bin/apport-unpack.py:22
#, python-format
msgid "Usage: %s <report> <target directory>"
msgstr "ئىشلىتىش ئۇسۇلى: %s <مەلۇمات> <نىشان مۇندەرىجە>"

#: ../debian/tmp/usr/bin/apport-unpack.py:46 ../bin/apport-unpack.py:46
msgid "Destination directory exists and is not empty."
msgstr "نىشان مۇندەرىجە بار ھەم بوش ئەمەس."

#, python-format
#~ msgid "Sorry, the program \"%s\" closed unexpectedly."
#~ msgstr "كەچۈرۈڭ، پروگرامما «%s» ئويلىمىغان يەردىن تاقىلىپ قالدى."

#, python-format
#~ msgid "Sorry, the package \"%s\" failed to install or upgrade."
#~ msgstr "كەچۈرۈڭ، بوغچا «%s» نى ئورنىتىش ياكى يۈكسەلدۈرۈش مەغلۇپ بولدى."

#~ msgid "Your system encountered a serious kernel problem."
#~ msgstr "سىستېمىڭىزنىڭ يادروسىدا(kernel) ئېغىر مەسىلە يۈز بەردى."

#~ msgid "Kernel problem"
#~ msgstr "يادرو(kernel) دىكى مەسىلە"

#~ msgid "Send this data to the developers?"
#~ msgstr "بۇ سانلىق-مەلۇماتلارنى ئىجادىيەتچىگە ئەۋەتسۇنمۇ؟"

#, no-c-format
#~ msgid ""
#~ "<span weight=\"bold\" size=\"larger\">Sorry, the package \"%s\" failed to "
#~ "install or upgrade.</span>"
#~ msgstr ""
#~ "<span weight=\"bold\" size=\"larger\">كەچۈرۈڭ، بوغچا «%s» نى ئورنىتىش ياكى "
#~ "يۈكسەلدۈرۈش مەغلۇپ بولدى.</span>"

#~ msgid "Package problem"
#~ msgstr "بوغچىدىكى مەسىلە"

#, python-format
#~ msgid "This is not a genuine %s package"
#~ msgstr "بۇ رەسمىي  %s بوغچىسى ئەمەس"

#, python-format
#~ msgid "The package \"%s\" failed to install or upgrade."
#~ msgstr "بوغچا «%s» نى ئورنىتىش ياكى يېڭىلاش مەغلۇپ بولدى."

#, python-format
#~ msgid "Sorry, the application %s has closed unexpectedly."
#~ msgstr "كەچۈرۈڭ بۇ %s ئەپ تاسادىپىي تاقالدى."
