# Uighur translation for apport
# Copyright (c) 2009 Rosetta Contributors and Canonical Ltd 2009
# This file is distributed under the same license as the apport package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2009.
#
msgid ""
msgstr ""
"Project-Id-Version: apport\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2013-05-21 12:15+0200\n"
"PO-Revision-Date: 2012-11-05 05:13+0000\n"
"Last-Translator: bilgeturghun <bilgeks@gmail.com>\n"
"Language-Team: Uighur <ug@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2013-07-19 05:11+0000\n"
"X-Generator: Launchpad (build 16696)\n"
"Language: ug\n"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:124
#: ../apport/ui.py:124
msgid "This package does not seem to be installed correctly"
msgstr "مەزكۇر بوغچا توغرا ئورنىتىلمىغاندەك قىلىدۇ"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:128
#: ../apport/ui.py:128
#, python-format
msgid ""
"This is not an official %s package. Please remove any third party package "
"and try again."
msgstr ""
"بۇ رەسمىي %s بوغچىسى ئەمەس. ئۈچىنچى تەرەپ بوغچىسىنى چىقىرىۋېتىپ، قايتا سىناڭ."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:145
#: ../apport/ui.py:145
#, python-format
msgid ""
"You have some obsolete package versions installed. Please upgrade the "
"following packages and check if the problem still occurs:\n"
"\n"
"%s"
msgstr ""
"بەزىبىر كونا بوغچىلار بار ئىكەن. تۆۋەندىكى بوغچىلارنى يۈكسەلدۈرگەندىن كېيىن "
"يەنە تەكشۈرۈپ كۆرۈڭ:\n"
"\n"
"%s"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:251
#: ../apport/ui.py:251
msgid "unknown program"
msgstr "نامەلۇم پروگرامما"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:252
#: ../apport/ui.py:252
#, python-format
msgid "Sorry, the program \"%s\" closed unexpectedly"
msgstr "كەچۈرۈڭ، پروگرامما  «%s» ئويلىمىغان يەردىن تاقىلىپ قالدى"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:254
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1256
#: ../apport/ui.py:254 ../apport/ui.py:1256
#, python-format
msgid "Problem in %s"
msgstr "مەسىلە %s نىڭدا"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:255
#: ../apport/ui.py:255
msgid ""
"Your computer does not have enough free memory to automatically analyze the "
"problem and send a report to the developers."
msgstr ""
"مەسىلىنى ئاپتوماتىك ئانالىز قىلىش ۋە ئىجادىيەتچىگە مەلۇمات يوللاشقا كېرەكلىك "
"ئەسلەك يېتەرلىك ئەمەس ئىكەن."

#. package does not exist
#: ../debian/tmp/usr/share/apport/testsuite/test_ui.py:268
#: ../debian/tmp/usr/share/apport/testsuite/test_ui.py:285
#: ../debian/tmp/usr/share/apport/testsuite/test_ui.py:1052
#: ../debian/tmp/usr/share/apport/testsuite/test_ui.py:1072
#: ../debian/tmp/usr/share/apport/testsuite/test_ui.py:1083
#: ../debian/tmp/usr/share/apport/testsuite/test_ui.py:1094
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:270
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:276
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:282
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:325
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:333
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:462
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:465
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:666
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1069
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1210
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1214
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1233
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1239
#: ../apport/ui.py:270 ../apport/ui.py:276 ../apport/ui.py:282
#: ../apport/ui.py:325 ../apport/ui.py:333 ../apport/ui.py:462
#: ../apport/ui.py:465 ../apport/ui.py:666 ../apport/ui.py:1069
#: ../apport/ui.py:1210 ../apport/ui.py:1214 ../apport/ui.py:1233
#: ../apport/ui.py:1239
msgid "Invalid problem report"
msgstr "مەلۇمات ئىناۋەتسىز"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:271
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1216
#: ../apport/ui.py:271 ../apport/ui.py:1216
msgid "This problem report is damaged and cannot be processed."
msgstr "بوغچا بۇزۇلغان بولغاچقا بىر تەرەپ قىلغىلى بولمىدى."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:277
#: ../apport/ui.py:277
msgid "The report belongs to a package that is not installed."
msgstr "مەلۇمات ئورنىتىلمىغان بوغچىغا تەۋە ئىكەن."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:283
#: ../apport/ui.py:283
msgid "An error occurred while attempting to process this problem report:"
msgstr ""
"بۇ مەسىلە ھەققىدىكى مەلۇماتنى بىر تەرەپ قىلاي دېگەندە  خاتالىق يۈز بەردى:"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:326
#: ../apport/ui.py:326
msgid "You are not allowed to access this problem report."
msgstr "بۇ مەسىلىنى مەلۇم قىلىش ھوقۇقىڭىز يوق."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:329
#: ../apport/ui.py:329
msgid "Error"
msgstr "خاتالىق"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:330
#: ../apport/ui.py:330
msgid "There is not enough disk space available to process this report."
msgstr "مەزكۇر مەلۇماتنى بىر تەرەپ قىلىشقا كېرەكلىك دىسكا بوشلۇقى يوق."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:414
#: ../apport/ui.py:414
msgid "No package specified"
msgstr "بوغچا كۆرسىتىلمىگەن."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:415
#: ../apport/ui.py:415
msgid ""
"You need to specify a package or a PID. See --help for more information."
msgstr ""
"بوغچا ياكى بىر PID نى كۆرسىتىڭ. تەپسىلاتلار ئۈچۈن --help نى ئىشلىتىڭ."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:432
#: ../apport/ui.py:432
msgid "Invalid PID"
msgstr "ئىناۋەتسىز PID"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:433
#: ../apport/ui.py:433
msgid "The specified process ID does not belong to a program."
msgstr "كۆرسىتىلگەن PID مەزكۇر پروگراممىنىڭ PID ئەمەس."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:441
#: ../apport/ui.py:441
msgid "Permission denied"
msgstr "ھوقۇقىڭىز يەتمىدى"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:442
#: ../apport/ui.py:442
msgid ""
"The specified process does not belong to you. Please run this program as the "
"process owner or as root."
msgstr ""
"بۇ سىزنىڭ پروگراممىڭىز ئەمەس. مەزكۇر پروگراممىنى ئۆزىڭىزنىڭ ياكى root نىڭ "
"ھوقۇقىدا ئىجرا قىلدۇرۇڭ."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:463
#: ../apport/ui.py:463
#, python-format
msgid "Symptom script %s did not determine an affected package"
msgstr "ئەھۋال قوليازما %s تەسىر كۆرسىتىدىغان بوغچىنى بەلگىلىمىگەن"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:466
#: ../apport/ui.py:466
#, python-format
msgid "Package %s does not exist"
msgstr "بوغچا %s مەۋجۇت ئەمەس"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:490
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:678
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:683
#: ../apport/ui.py:490 ../apport/ui.py:678 ../apport/ui.py:683
msgid "Cannot create report"
msgstr "مەلۇمات قۇرالمىدى"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:505
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:551
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:568
#: ../apport/ui.py:505 ../apport/ui.py:551 ../apport/ui.py:568
msgid "Updating problem report"
msgstr "مەلۇماتىنى يېڭىلاۋاتىدۇ"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:506
#: ../apport/ui.py:506
msgid ""
"You are not the reporter or subscriber of this problem report, or the report "
"is a duplicate or already closed.\n"
"\n"
"Please create a new report using \"apport-bug\"."
msgstr ""
"سىز بۇ مەسىلىنى مەلۇم قىلغان كىشى ئەمەس، ياكى مەلۇمات تەكرارلانغان ياكى "
"ئاللىقاچان تاقالغان.\n"
"\n"
"«apport-bug» نى ئىشلىتىپ يېڭىدىن مەلۇمات تەييارلاڭ."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:515
#: ../apport/ui.py:515
msgid ""
"You are not the reporter of this problem report. It is much easier to mark a "
"bug as a duplicate of another than to move your comments and attachments to "
"a new bug.\n"
"\n"
"Subsequently, we recommend that you file a new bug report using \"apport-"
"bug\" and make a comment in this bug about the one you file.\n"
"\n"
"Do you really want to proceed?"
msgstr ""
"سىز بۇ مەسىلىنى مەلۇم قىلغۇچى ئەمەس. يېڭى كەمتۈك دەپ مەلۇم قىلغاندىن كۆرە، "
"باشقا كەمتۈك بىلەن ئوخشاش دەپ بەلگە قويۇش تېخىمۇ ئاسان.\n"
"\n"
"ئارقىدىن، «apport-bug» نى ئىشلىتىپ، كەمتۈك مەلۇم قىلىپ، مەلۇماتنىڭ ئىچىگە "
"كەمتۈك ھەققىدىكى ئىزاھاتنى يېزىشىڭىزنى تەۋسىيە قىلىمىز.\n"
"\n"
"راستلا داۋاملاشتۇرامسىز؟"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:552
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:569
#: ../apport/ui.py:552 ../apport/ui.py:569
msgid "No additional information collected."
msgstr "قوشۇمچە ئۇچۇرلار توپلانمىدى."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:620
#: ../apport/ui.py:620
msgid "What kind of problem do you want to report?"
msgstr "قانداق مەسىلىنى مەلۇم قىلماقچى؟"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:637
#: ../apport/ui.py:637
msgid "Unknown symptom"
msgstr "نامەلۇم ھادىسە"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:638
#: ../apport/ui.py:638
#, python-format
msgid "The symptom \"%s\" is not known."
msgstr "ھادىسە «%s» نامەلۇم."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:669
#: ../apport/ui.py:669
msgid ""
"After closing this message please click on an application window to report a "
"problem about it."
msgstr ""
"ئۇچۇرنى ياپقاندىن كېيىن پروگرامما كۆزنىكىنى چېكىپ، بۇ مەسىلىنى مەلۇم قىلىڭ."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:679
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:684
#: ../apport/ui.py:679 ../apport/ui.py:684
msgid "xprop failed to determine process ID of the window"
msgstr "xprop كۆزنەكنىڭ ئىجرا ID سىنى تېپىشتا مەغلۇپ بولدى"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:698
#: ../apport/ui.py:698
msgid "%prog <report number>"
msgstr "%prog <مەلۇمات نومۇرى>"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:700
#: ../apport/ui.py:700
msgid "Specify package name."
msgstr "بوغچا ئاتىنى كۆرسىتىپ بېرىڭ."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:702
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:753
#: ../apport/ui.py:702 ../apport/ui.py:753
msgid "Add an extra tag to the report. Can be specified multiple times."
msgstr "دوكلاتقا يېڭىدىن خەتكۈش قوشۇڭ، كۆپ قېتىم بەلگىلەشكە بولىدۇ."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:732
#: ../apport/ui.py:732
msgid ""
"%prog [options] [symptom|pid|package|program path|.apport/.crash file]"
msgstr ""
"%prog [options] [symptom|pid|package|program path|.apport/.crash file]"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:735
#: ../apport/ui.py:735
msgid ""
"Start in bug filing mode. Requires --package and an optional --pid, or just "
"a --pid. If neither is given, display a list of known symptoms. (Implied if "
"a single argument is given.)"
msgstr ""
"كەمتۈك يېزىش ھالىتىدە باشلايدۇ. ئىجرا قىلغاندا --package ۋە --pid ياكى "
"پەقەتلا --pid تاللانمىسىنى يازسىلا بولىدۇ. ئەگەر ھېچقايسى يېزىلمىسا، "
"كۆرۈلگەن ئالامەتلەرنىڭ تىزىمىنى كۆرسىتىدۇ. (پەقەت يالغۇز ئارگۇمېنت "
"بېرىلگەندىلا.)"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:737
#: ../apport/ui.py:737
msgid "Click a window as a target for filing a problem report."
msgstr "خاتالىق دوكلاتىنى تولدۇرۇش ئۈچۈن كۆزنەكنى نىشان قىلىپ چېكىڭ"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:739
#: ../apport/ui.py:739
msgid "Start in bug updating mode. Can take an optional --package."
msgstr ""
"كەمتۈك يېڭىلاش ھالىتىدە قوزغىتىش. --package دېگەن تاللانمىنى ئىشلىتىشكە "
"بولىدۇ."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:741
#: ../apport/ui.py:741
msgid ""
"File a bug report about a symptom. (Implied if symptom name is given as only "
"argument.)"
msgstr ""
"ھادىسە ھەققىدە مەلۇمات تەييارلاڭ. (Implied if symptom name is given as only "
"argument)"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:743
#: ../apport/ui.py:743
msgid ""
"Specify package name in --file-bug mode. This is optional if a --pid is "
"specified. (Implied if package name is given as only argument.)"
msgstr ""
"--file-bug ھالىتىدە بوغچا ئاتىنى كۆرسىتىڭ. ئەگەر --pid كۆرسىتىلگەن بولسا، "
"بۇنى كۆرسەتمىسىمۇ بولىدۇ.(Implied if package name is given as only argument.)"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:745
#: ../apport/ui.py:745
msgid ""
"Specify a running program in --file-bug mode. If this is specified, the bug "
"report will contain more information.  (Implied if pid is given as only "
"argument.)"
msgstr ""
"--file-bug  ھالىتىدە ئىجرا بولۇۋاتقان پروگراممىنى كۆرسىتىڭ. ئەگەر بۇ "
"كۆرسىتىلسە، كەمتۈك مەلۇماتىغا تېخىمۇ كۆپ ئۇچۇرلار قوشۇلىدۇ. (Implied if pid "
"is given as only argument.)"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:747
#: ../apport/ui.py:747
msgid "The provided pid is a hanging application."
msgstr ""
"تەمىنلەنگەن pid بولسا بىر ئېسىلىپ قالغان(توختاپ قالغان) پروگرامما ئىكەن."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:749
#: ../apport/ui.py:749
#, python-format
msgid ""
"Report the crash from given .apport or .crash file instead of the pending "
"ones in %s. (Implied if file is given as only argument.)"
msgstr ""
"چاتاق مەلۇماتىنى  %s نىڭدىكى كۈتۈپ تۇرغان ھۆججەتنى ئەمەس بەلكى بېرىلگەن  "
".apport ياكى .crash ھۆججىتىنى ئىشلىتىپ يوللاش(پەقەت ھۆججەت ئاتى ئارگۇمېنت "
"شەكىلدە بېرىلگەندىلا.)"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:751
#: ../apport/ui.py:751
msgid ""
"In bug filing mode, save the collected information into a file instead of "
"reporting it. This file can then be reported later on from a different "
"machine."
msgstr ""
"كەمتۈك يېزىش ھالىتىدە، توپلانغان ئۇچۇرلارنى مەلۇم قىلماي ھۆججەتكە ساقلاپ "
"قويۇشقا، بۇ ھۆججەتنى كېيىن باشقا كومپيۇتېر ئارقىلىق يوللاشقىمۇ بولىدۇ."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:755
#: ../apport/ui.py:755
msgid "Print the Apport version number."
msgstr "Apport نىڭ نەشر نومۇرىنى بېسىپ چىقىرىدۇ."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:889
#: ../apport/ui.py:889
msgid ""
"This will launch apport-retrace in a terminal window to examine the crash."
msgstr ""
"crash نى تەكشۈرۈش ئۈچۈن apport-retrace تېرمىنال كۆزنىكىدە ئىجرا بولىدۇ."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:890
#: ../apport/ui.py:890
msgid "Run gdb session"
msgstr "gdb ئەڭگىمەسىنى ئىجرا قىلىش"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:891
#: ../apport/ui.py:891
msgid "Run gdb session without downloading debug symbols"
msgstr "سازلاش بەلگىلىرىنى چۈشۈرمەيلا gdb ئەڭگىمەسىنى ئىجرا قىلىش"

#. TRANSLATORS: %s contains the crash report file name
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:893
#: ../apport/ui.py:893
#, python-format
msgid "Update %s with fully symbolic stack trace"
msgstr "%s نى تولۇق بەلگىلەر بىلەن يېڭىلاش"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:966
#: ../apport/ui.py:966
#, python-format
msgid ""
"The problem happened with the program %s which changed since the crash "
"occurred."
msgstr "توقۇنۇشتا ئۆزگەرگەن پروگرامما %s تە خاتالىق كۆرۈلدى."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1070
#: ../apport/ui.py:1070
msgid "Could not determine the package or source package name."
msgstr "بوغچا ياكى مەنبە كود بوغچىسىنىڭ نامىنى بېكىتكىلى بولمىدى."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1088
#: ../apport/ui.py:1088
msgid "Unable to start web browser"
msgstr "توركۆرگۈنى قوزغاتقىلى بولمىدى"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1089
#: ../apport/ui.py:1089
#, python-format
msgid "Unable to start web browser to open %s."
msgstr "%s نى كۆرىدىغان توركۆرگۈنى قوزغاتقىلى بولمىدى."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1164
#: ../apport/ui.py:1164
#, python-format
msgid "Please enter your account information for the %s bug tracking system"
msgstr "كەمتۈك باشقۇرۇش سىستېمىسى %s غا ھېسابات ئۇچۇرىڭىزنى كىرگۈزۈڭ."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1176
#: ../apport/ui.py:1176
msgid "Network problem"
msgstr "توردىكى مەسىلە"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1178
#: ../apport/ui.py:1178
msgid ""
"Cannot connect to crash database, please check your Internet connection."
msgstr "crash ساندىنىغا باغلىنالمىدى، ئىنتېرنېت باغلىنىشىنى تەكشۈرۈپ كۆرۈڭ."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1205
#: ../apport/ui.py:1205
msgid "Memory exhaustion"
msgstr "ئەسلەك يېتىشمىدى"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1206
#: ../apport/ui.py:1206
msgid "Your system does not have enough memory to process this crash report."
msgstr ""
"سىستېمىڭىزدا مەزكۇر crash مەلۇماتىنى بىر تەرەپ قىلىشقا يېتەرلىك ئەسلەك يوق."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1229
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1238
#: ../apport/ui.py:1229 ../apport/ui.py:1238
msgid ""
"This problem report applies to a program which is not installed any more."
msgstr "بۇ دوكلات زادىلا ئورنىتىلىپ باقمىغان پروگراممىغا ئىشلىتىلىدۇ."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1259
#: ../apport/ui.py:1259
#, python-format
msgid ""
"The problem cannot be reported:\n"
"\n"
"%s"
msgstr ""
"مەسىلىنى مەلۇم قىلغىلى بولمىدى:\n"
"\n"
"%s"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1315
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1322
#: ../apport/ui.py:1315 ../apport/ui.py:1322
msgid "Problem already known"
msgstr "مەسىلە ئاللىقاچان ئايدىڭلاشقان"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1316
#: ../apport/ui.py:1316
msgid ""
"This problem was already reported in the bug report displayed in the web "
"browser. Please check if you can add any further information that might be "
"helpful for the developers."
msgstr ""
"توركۆرگۈدىكى كەمتۈك دوكلاتىدا بۇ مەسىلە ئاللىقاچان مەلۇم قىلىنغان. تەكشۈرۈپ "
"كۆرۈڭ، ئەگەر سىزنىڭ مەلۇماتىڭىزدا تېخىمۇ كۆپرەك ئۇچۇرلار بار بولسا "
"ئىجادىيەتچىلەر ئۈچۈن تېخىمۇ پايدىلىق بولاتتى."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1323
#: ../apport/ui.py:1323
msgid "This problem was already reported to developers. Thank you!"
msgstr "مەسىلە ئىجادىيەتچىلەرگە مەلۇم قىلىندى. سىزگە تەشەككۈر!"

#: ../debian/tmp/usr/bin/apport-cli.py:74 ../bin/apport-cli.py:74
msgid "Press any key to continue..."
msgstr "خالىغان كۇنۇپكىنى باسسىڭىز داۋاملىشىدۇ..."

#: ../debian/tmp/usr/bin/apport-cli.py:81 ../bin/apport-cli.py:81
msgid "What would you like to do? Your options are:"
msgstr "نېمە قىلغۇڭىز بار؟ سىز تۆۋەندىكىلەرنى قىلالايسىز:"

#: ../debian/tmp/usr/bin/apport-cli.py:85 ../bin/apport-cli.py:85
#, python-format
msgid "Please choose (%s):"
msgstr "تاللاڭ(%s):"

#: ../debian/tmp/usr/bin/apport-cli.py:145 ../bin/apport-cli.py:145
#, python-format
msgid "(%i bytes)"
msgstr "(%i بايت)"

#: ../gtk/apport-gtk.py:138 ../debian/tmp/usr/bin/apport-cli.py:147
#: ../debian/tmp/usr/share/apport/apport-kde.py:338 ../bin/apport-cli.py:147
#: ../kde/apport-kde.py:338 ../debian/tmp/usr/share/apport/apport-gtk.py:138
msgid "(binary data)"
msgstr "(ئىككىلىك سانلىق-مەلۇمات)"

#: ../gtk/apport-gtk.py:173 ../debian/tmp/usr/bin/apport-cli.py:175
#: ../debian/tmp/usr/share/apport/apport-kde.py:162 ../bin/apport-cli.py:175
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:282
#: ../kde/apport-kde.py:162 ../debian/tmp/usr/share/apport/apport-gtk.py:173
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:404
msgid "Send problem report to the developers?"
msgstr "بۇ مەلۇماتنى ئىجادىيەتچىگە ئەۋەتسۇنمۇ؟"

#: ../debian/tmp/usr/bin/apport-cli.py:176 ../bin/apport-cli.py:176
msgid ""
"After the problem report has been sent, please fill out the form in the\n"
"automatically opened web browser."
msgstr ""
"مەلۇماتنى ئەۋەتىپ بولغاندىن كېيىن \n"
"توركۆرگۈدە ئېچىلغان بەتتىكى جەدۋەلنى تولدۇرۇڭ."

#: ../debian/tmp/usr/bin/apport-cli.py:179 ../bin/apport-cli.py:179
#, python-format
msgid "&Send report (%s)"
msgstr "مەلۇمات (%s) نى ئەۋەت(&S)"

#: ../debian/tmp/usr/bin/apport-cli.py:183 ../bin/apport-cli.py:183
msgid "&Examine locally"
msgstr "يەرلىكتە تەكشۈر(&E)"

#: ../debian/tmp/usr/bin/apport-cli.py:187 ../bin/apport-cli.py:187
msgid "&View report"
msgstr "مەلۇمات كۆرسەت(&V)"

#: ../debian/tmp/usr/bin/apport-cli.py:188 ../bin/apport-cli.py:188
msgid "&Keep report file for sending later or copying to somewhere else"
msgstr ""
"كېيىن يەنە باشقىلارغا ئەۋەتىش ياكى كۆچۈرۈپ بېرىش ئۈچۈن مەلۇمات ھۆججىتى "
"ساقلاپ قوي(&K)"

#: ../debian/tmp/usr/bin/apport-cli.py:189 ../bin/apport-cli.py:189
msgid "Cancel and &ignore future crashes of this program version"
msgstr ""
"پروگراممىنىڭ مەزكۇر نەشرىدە بۇنىڭدىن كېلىپ چىققان crashes نى ئەمەلدىن قالدۇر "
"ياكى پىسەنت قىلما(&I)"

#: ../debian/tmp/usr/bin/apport-cli.py:191
#: ../debian/tmp/usr/bin/apport-cli.py:268
#: ../debian/tmp/usr/bin/apport-cli.py:300
#: ../debian/tmp/usr/bin/apport-cli.py:321 ../bin/apport-cli.py:191
#: ../bin/apport-cli.py:268 ../bin/apport-cli.py:300 ../bin/apport-cli.py:321
msgid "&Cancel"
msgstr "ئەمەلدىن قالدۇر(&C)"

#: ../debian/tmp/usr/bin/apport-cli.py:219 ../bin/apport-cli.py:219
msgid "Problem report file:"
msgstr "مەلۇمات ھۆججىتى:"

#: ../debian/tmp/usr/bin/apport-cli.py:225
#: ../debian/tmp/usr/bin/apport-cli.py:230 ../bin/apport-cli.py:225
#: ../bin/apport-cli.py:230
msgid "&Confirm"
msgstr "جەزملە(&C)"

#: ../debian/tmp/usr/bin/apport-cli.py:229 ../bin/apport-cli.py:229
#, python-format
msgid "Error: %s"
msgstr "خاتالىق: %s"

#: ../debian/tmp/usr/bin/apport-cli.py:235
#: ../debian/tmp/usr/share/apport/apport-kde.py:383 ../bin/apport-cli.py:235
#: ../kde/apport-kde.py:383
msgid "Collecting problem information"
msgstr "مەسىلىلەرگە ئائىت ئۇچۇرلارنى توپلاۋاتىدۇ"

#: ../debian/tmp/usr/bin/apport-cli.py:236 ../bin/apport-cli.py:236
msgid ""
"The collected information can be sent to the developers to improve the\n"
"application. This might take a few minutes."
msgstr ""
"ئىجادىيەتچىلەرنىڭ پروگراممىنى مۇكەممەللەشتۈرۈشى ئۈچۈن \n"
"توپلانغان ئۇچۇرلارنى ئەۋەتىدۇ. بۇنىڭغا ئازراق ۋاقىت كېتىدۇ."

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:13
#: ../debian/tmp/usr/bin/apport-cli.py:248
#: ../debian/tmp/usr/share/apport/apport-kde.py:411 ../gtk/apport-gtk.ui.h:13
#: ../bin/apport-cli.py:248 ../kde/apport-kde.py:411
msgid "Uploading problem information"
msgstr "مەسىلىلەر ھەققىدىكى ئۇچۇرلارنى يېڭىلاۋاتىدۇ"

#: ../debian/tmp/usr/bin/apport-cli.py:249 ../bin/apport-cli.py:249
msgid ""
"The collected information is being sent to the bug tracking system.\n"
"This might take a few minutes."
msgstr ""
"توپلانغان ئۇچۇرلارنى كەمتۈك باشقۇرۇش سىستېمىسىغا ئەۋەتىدۇ.\n"
"بۇنىڭغا ئازراق ۋاقىت كېتىدۇ."

#: ../debian/tmp/usr/bin/apport-cli.py:299 ../bin/apport-cli.py:299
msgid "&Done"
msgstr "تامام(&D)"

#: ../debian/tmp/usr/bin/apport-cli.py:305 ../bin/apport-cli.py:305
msgid "none"
msgstr "يوق"

#: ../debian/tmp/usr/bin/apport-cli.py:306 ../bin/apport-cli.py:306
#, python-format
msgid "Selected: %s. Multiple choices:"
msgstr "تاللانغىنى : %s. كوپنى تاللاش:"

#: ../debian/tmp/usr/bin/apport-cli.py:322 ../bin/apport-cli.py:322
msgid "Choices:"
msgstr "تاللاشلار:"

#: ../debian/tmp/usr/bin/apport-cli.py:336 ../bin/apport-cli.py:336
msgid "Path to file (Enter to cancel):"
msgstr "ھۆججەتنىڭ يولى(بولدى قىلىش ئۈچۈن قايتۇرۇش كۇنۇپكىسىنى بېسىڭ):"

#: ../debian/tmp/usr/bin/apport-cli.py:342 ../bin/apport-cli.py:342
msgid "File does not exist."
msgstr "ھۆججەت مەۋجۇت ئەمەس."

#: ../debian/tmp/usr/bin/apport-cli.py:344 ../bin/apport-cli.py:344
msgid "This is a directory."
msgstr "بۇ بىر مۇندەرىجە."

#: ../debian/tmp/usr/bin/apport-cli.py:350 ../bin/apport-cli.py:350
msgid "To continue, you must visit the following URL:"
msgstr "داۋاملاشتۇرۇش ئۈچۈن تۆۋەندىكى URL نى كۆرۈشىڭىز كېرەك:"

#: ../debian/tmp/usr/bin/apport-cli.py:352 ../bin/apport-cli.py:352
msgid ""
"You can launch a browser now, or copy this URL into a browser on another "
"computer."
msgstr ""
"ئەمدى توركۆرگۈنى قوزغىتىڭ ياكى، URL نى باشقا كومپيۇتېردىكى توركۆرگۈگە "
"كۆچۈرۈڭ."

#: ../debian/tmp/usr/bin/apport-cli.py:354 ../bin/apport-cli.py:354
msgid "Launch a browser now"
msgstr "ھازىرلا توركۆرگۈنى قوزغىتىش"

#: ../debian/tmp/usr/bin/apport-cli.py:368 ../bin/apport-cli.py:368
msgid "No pending crash reports. Try --help for more information."
msgstr ""
"تېخى بىر تەرەپ قىلىنمىغان crash ھەققىدىكى مەلۇمات يوق. --help نى ئىشلەتسىڭىز "
"تېخىمۇ كوپ ئۇچۇرغا ئېرىشەلەيسىز."

#: ../debian/tmp/usr/share/apport/apportcheckresume.py:68
#: ../data/apportcheckresume.py:68
msgid ""
"This occured during a previous suspend and prevented it from resuming "
"properly."
msgstr ""
"بۇ ئالدىنقى قېتىملىق توڭلىتىش جەريانىدا يۈز بەرگەن بولۇپ، قايتا باشلاشقا "
"بولمىدى."

#: ../debian/tmp/usr/share/apport/apportcheckresume.py:70
#: ../data/apportcheckresume.py:70
msgid ""
"This occured during a previous hibernate and prevented it from resuming "
"properly."
msgstr ""
"بۇ ئالدىنقى قېتىملىق ئۈچەككە كىرگۈزۈش جەريانىدا يۈز بەرگەن بولۇپ، قايتا "
"باشلاشقا بولمىدى."

#: ../debian/tmp/usr/share/apport/apportcheckresume.py:75
#: ../data/apportcheckresume.py:75
msgid ""
"The resume processing hung very near the end and will have appeared to have "
"completed normally."
msgstr ""
"ئەسلىگە قايتۇرۇش باسقۇچى ئاخىرلىشاي دەپ قالدى، بۇنداق بولغاندا نورمال "
"تاماملىنىدۇ."

#: ../debian/tmp/usr/bin/apport-retrace.py:31 ../bin/apport-retrace.py:31
msgid "%prog [options] <apport problem report | crash ID>"
msgstr "%prog [options] <apport problem report | crash ID>"

#: ../debian/tmp/usr/bin/apport-retrace.py:33 ../bin/apport-retrace.py:33
msgid "Do not put the new traces into the report, but write them to stdout."
msgstr "بۇ يېڭى چىققانلىرىنى مەلۇماتقا يازماي stdout قا يازسۇن."

#: ../debian/tmp/usr/bin/apport-retrace.py:35 ../bin/apport-retrace.py:35
msgid ""
"Start an interactive gdb session with the report's core dump (-o ignored; "
"does not rewrite report)"
msgstr ""
"مەلۇماتنىڭ غول تۆكمىسىگە نىسبەتەن تەسىرلىشىشچان gdb ئەڭگىمەسىنى باشلايدۇ(-o "
"غا پەرۋا قىلمايدۇ؛ مەلۇماتنى قاپلىمايدۇ)"

#: ../debian/tmp/usr/bin/apport-retrace.py:37 ../bin/apport-retrace.py:37
msgid ""
"Write modified report to given file instead of changing the original report"
msgstr "ئەسلىدىكى مەلۇماتقا يازماي كۆرسىتىلگەن ھۆججەتكە يازسۇن."

#: ../debian/tmp/usr/bin/apport-retrace.py:39 ../bin/apport-retrace.py:39
msgid "Remove the core dump from the report after stack trace regeneration"
msgstr ""
"stack ئىزلىشى قايتا ھاسىللانغاندىن كېيىن، غول تۆكمىنى(core dump) مەلۇماتتىن "
"چىقىرىۋېتىش"

#: ../debian/tmp/usr/bin/apport-retrace.py:41 ../bin/apport-retrace.py:41
msgid "Override report's CoreFile"
msgstr "دوكلاتنىڭ CoreFile نى قاپلاش"

#: ../debian/tmp/usr/bin/apport-retrace.py:43 ../bin/apport-retrace.py:43
msgid "Override report's ExecutablePath"
msgstr "دوكلاتنىڭ ExecutablePath نى قاپلاش"

#: ../debian/tmp/usr/bin/apport-retrace.py:45 ../bin/apport-retrace.py:45
msgid "Override report's ProcMaps"
msgstr "دوكلاتنىڭ ProcMaps نى قاپلاش"

#: ../debian/tmp/usr/bin/apport-retrace.py:47 ../bin/apport-retrace.py:47
msgid "Rebuild report's Package information"
msgstr "دوكلاتنىڭ بوغچا ئۇچۇرىنى قايتا قۇرۇش"

#: ../debian/tmp/usr/bin/apport-retrace.py:49 ../bin/apport-retrace.py:49
msgid ""
"Build a temporary sandbox and download/install the necessary packages and "
"debug symbols in there; without this option it assumes that the necessary "
"packages and debug symbols are already installed in the system. The argument "
"points to the packaging system configuration base directory; if you specify "
"\"system\", it will use the system configuration files, but will then only "
"be able to retrace crashes that happened on the currently running release."
msgstr ""
"ۋاقتىنچە قۇم ساندۇقى قۇرىدۇ ھەم قاچىلاش بوغچىسىنى يۈكلەيدۇ/قاچىلايدۇ.ئەگەر "
"بۇ تاللانما ئىشلىتىلمىسە، سىستېمىغا لازىملىق دېتالنى قاچىلايدۇ. ئەگەر سىز "
"سىستېما بەلگىلىمىسىڭىز، سىستېما سەپلىمىسىنى ئىشلىتىدۇ، شۇنىڭ بىلەن ئىجرا "
"قىلىنىۋاتقان سىستېمىنى ھالاك قىلىدۇ."

#: ../debian/tmp/usr/bin/apport-retrace.py:51 ../bin/apport-retrace.py:51
msgid ""
"Report download/install progress when installing packages into sandbox"
msgstr ""
"بوغچىلارنى قۇم خالتىسى ئىچىگە ئورناتقاندىكى چۈشۈرۈش/ئورنىتىش جەريانىنى مەلۇم "
"قىلىش"

#: ../debian/tmp/usr/bin/apport-retrace.py:53 ../bin/apport-retrace.py:53
msgid "Prepend timestamps to log messages, for batch operation"
msgstr ""
"ئۇچۇر خاتىرىلەشتىن بۇرۇن ۋاقىتنى خاتىرىلەڭ، بۇ قېتىملىق مەشغۇلاتنى "
"تەمىنلەيدۇ."

#: ../debian/tmp/usr/bin/apport-retrace.py:55 ../bin/apport-retrace.py:55
msgid "Cache directory for packages downloaded in the sandbox"
msgstr "قۇم خالتىسى ئىچىگە چۈشۈرۈلگەن بوغچىلارنىڭ غەملەك مۇندەرىجىسى"

#: ../debian/tmp/usr/bin/apport-retrace.py:57 ../bin/apport-retrace.py:57
msgid ""
"Directory for unpacked packages. Future runs will assume that any already "
"downloaded package is also extracted to this sandbox."
msgstr ""
"يېيىلمىغان بوغچىلارنىڭ مۇندەرىجىسى. كېيىن ئىجرا قىلىدىغان چاغدا، چۈشۈرۈلگەن "
"بوغچىلار مۇشۇ يەرگە يېيىلىدۇ."

#: ../bin/apport-valgrind.py:66 ../debian/tmp/usr/bin/apport-retrace.py:59
#: ../debian/tmp/usr/bin/apport-valgrind.py:66 ../bin/apport-retrace.py:59
msgid ""
"Install an extra package into the sandbox (can be specified multiple times)"
msgstr ""
"قۇم خالتىسى ئىچىگە قوشۇمچە بوغچىنى ئورنىتىش(بىر قانچە قېتىم كۆرسىتىشكە "
"بولىدۇ)"

#: ../debian/tmp/usr/bin/apport-retrace.py:61 ../bin/apport-retrace.py:61
msgid ""
"Path to a file with the crash database authentication information. This is "
"used when specifying a crash ID to upload the retraced stack traces (only if "
"neither -g, -o, nor -s are specified)"
msgstr ""
"يىمىرىلىش ساندانىنى زىيارەت قىلىش ئۇچۇرى ھۆججىتىنىڭ يولىنى ئۆز ئىچىگە "
"ئالىدۇ. بۇ تاللانما مۇئەييەن يىمىرىلىش كودىدا  ئىزلاشنىڭ قايتۇرما سازلاش "
"ئۇچۇرى ئۈچۈن ئىشلىتىلىدۇ. (ئىشلەتكۈچى -g, -o, ياكى -s نى بەلگىلىگەن "
"بولمىسىلا)"

#: ../debian/tmp/usr/bin/apport-retrace.py:63 ../bin/apport-retrace.py:63
msgid ""
"Display retraced stack traces and ask for confirmation before sending them "
"to the crash database."
msgstr ""
"قايتۇرغان ئىزلاش ئۇچۇرىنى كۆرسىتىدۇ ھەمدە يىمىرىلىش ساندىنىغا يوللاش "
"يوللىماسلىقنى جەزملەشنى سورايدۇ."

#: ../debian/tmp/usr/bin/apport-retrace.py:65 ../bin/apport-retrace.py:65
msgid ""
"Path to the duplicate sqlite database (default: no duplicate checking)"
msgstr ""
"تەكرارلانغان sqlite ساندىنىنىڭ يولى.(كۆڭۈلدە تەكرارلىنىشنى تەكشۈرمەيدۇ)"

#: ../debian/tmp/usr/bin/apport-retrace.py:70 ../bin/apport-retrace.py:70
msgid "incorrect number of arguments; use --help for a short help"
msgstr ""
"argument لارنىڭ سانى توغرا ئەمەس. --help نى ئىشلىتىپ قىسقىچە چۈشەندۈرۈشىنى "
"كۆرۈڭ."

#: ../debian/tmp/usr/bin/apport-retrace.py:76 ../bin/apport-retrace.py:76
msgid "You cannot use -C without -S. Stopping."
msgstr ""

#: ../debian/tmp/usr/bin/apport-retrace.py:80 ../bin/apport-retrace.py:80
msgid ""
"you either need to do a local operation (-s, -g, -o) or supply an "
"authentication file (--auth); see --help for a short help"
msgstr ""
"يەرلىكتە مەشغۇلات قىلىشىڭىز (-s، -g، -o) ياكى سالاھىيەت دەلىللەش ھۆججىتىنى (-"
"-auth) تەمىنلىشىڭىز كېرەك. ئاددىي ياردەم ئۇچۇرىغا ئېرىشىش ئۈچۈن --help نى "
"ئىشلىتىڭ."

#. translators: don't translate y/n, apport currently only checks for "y"
#: ../debian/tmp/usr/bin/apport-retrace.py:114 ../bin/apport-retrace.py:114
msgid "OK to send these as attachments? [y/n]"
msgstr "بۇ قوشۇلما ھۆججەتلەرنى ئەۋەتسە بولامدۇ؟[y/n]"

#: ../gtk/apport-gtk-mime.desktop.in.h:1 ../kde/apport-kde-mime.desktop.in.h:1
#: ../kde/apport-kde.desktop.in.h:1 ../gtk/apport-gtk.desktop.in.h:1
msgid "Report a problem..."
msgstr "مەسىلىنى مەلۇم قىلىش..."

#: ../gtk/apport-gtk-mime.desktop.in.h:2 ../kde/apport-kde-mime.desktop.in.h:2
#: ../kde/apport-kde.desktop.in.h:2 ../gtk/apport-gtk.desktop.in.h:2
msgid "Report a malfunction to the developers"
msgstr "خاتالىقنى ئىجادىيەتچىگە مەلۇم قىلىدۇ"

#: ../data/kernel_oops.py:28 ../debian/tmp/usr/share/apport/kernel_oops.py:28
msgid "Your system might become unstable now and might need to be restarted."
msgstr ""
"سىستېمىڭىزنىڭ تۇراقسىز بولۇپ قېلىش ئېھتىماللىقى بار، قايتا قوزغىتىش "
"زۆرۈرىيىتى باردەك قىلىدۇ."

#: ../bin/apport-valgrind.py:37 ../debian/tmp/usr/bin/apport-valgrind.py:37
msgid "See man page for details."
msgstr ""

#: ../bin/apport-valgrind.py:43 ../debian/tmp/usr/bin/apport-valgrind.py:43
msgid "specify the log file name produced by valgrind"
msgstr ""

#: ../bin/apport-valgrind.py:46 ../debian/tmp/usr/bin/apport-valgrind.py:46
msgid ""
"reuse a previously created sandbox dir (SDIR) or, if it does not exist, "
"create it"
msgstr ""

#: ../bin/apport-valgrind.py:50 ../debian/tmp/usr/bin/apport-valgrind.py:50
msgid ""
"do  not  create  or reuse a sandbox directory for additional debug symbols "
"but rely only on installed debug symbols."
msgstr ""

#: ../bin/apport-valgrind.py:54 ../debian/tmp/usr/bin/apport-valgrind.py:54
msgid ""
"reuse a previously created cache dir (CDIR) or, if it does not exist, create "
"it"
msgstr ""

#: ../bin/apport-valgrind.py:58 ../debian/tmp/usr/bin/apport-valgrind.py:58
msgid ""
"report download/install progress when installing packages into sandbox"
msgstr ""

#: ../bin/apport-valgrind.py:62 ../debian/tmp/usr/bin/apport-valgrind.py:62
msgid ""
"the executable that is run under valgrind's memcheck tool  for memory leak "
"detection"
msgstr ""

#: ../bin/apport-valgrind.py:97 ../debian/tmp/usr/bin/apport-valgrind.py:97
#, python-format
msgid "Error: %s is not an executable. Stopping."
msgstr ""

#: ../gtk/apport-gtk.py:153 ../debian/tmp/usr/share/apport/apport-gtk.py:153
#, python-format
msgid "Sorry, the application %s has stopped unexpectedly."
msgstr "كەچۈرۈڭ، پروگرامما %s  تاسادىپىي توختاپ قالدى."

#: ../gtk/apport-gtk.py:156 ../debian/tmp/usr/share/apport/apport-gtk.py:156
#, python-format
msgid "Sorry, %s has closed unexpectedly."
msgstr "كەچۈرۈڭ، %s تاسادىپىي تاقالدى."

#: ../gtk/apport-gtk.py:161 ../debian/tmp/usr/share/apport/apport-kde.py:176
#: ../debian/tmp/usr/share/apport/apport-kde.py:217
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:106
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:250
#: ../kde/apport-kde.py:176 ../kde/apport-kde.py:217
#: ../debian/tmp/usr/share/apport/apport-gtk.py:161
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:108
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:300
#, python-format
msgid "Sorry, %s has experienced an internal error."
msgstr "كەچۈرۈڭ، %s ئىچكى خاتالىققا يولۇقتى."

#: ../gtk/apport-gtk.py:182 ../debian/tmp/usr/share/apport/apport-kde.py:170
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:288
#: ../kde/apport-kde.py:170 ../debian/tmp/usr/share/apport/apport-gtk.py:182
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:412
msgid "Send"
msgstr "يوللا"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:7 ../gtk/apport-gtk.py:200
#: ../gtk/apport-gtk.py:569 ../debian/tmp/usr/share/apport/apport-kde.py:271
#: ../gtk/apport-gtk.ui.h:7 ../kde/apport-kde.py:271
#: ../debian/tmp/usr/share/apport/apport-gtk.py:200
#: ../debian/tmp/usr/share/apport/apport-gtk.py:569
msgid "Show Details"
msgstr "تەپسىلاتلارنى كۆرسەت"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:10 ../gtk/apport-gtk.py:212
#: ../gtk/apport-gtk.py:280 ../gtk/apport-gtk.py:299
#: ../debian/tmp/usr/share/apport/apport-kde.py:210
#: ../debian/tmp/usr/share/apport/apport-kde.py:223 ../gtk/apport-gtk.ui.h:10
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:111
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:137
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:149
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:182
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:258
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:328
#: ../kde/apport-kde.py:210 ../kde/apport-kde.py:223
#: ../debian/tmp/usr/share/apport/apport-gtk.py:212
#: ../debian/tmp/usr/share/apport/apport-gtk.py:280
#: ../debian/tmp/usr/share/apport/apport-gtk.py:299
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:115
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:144
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:157
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:192
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:310
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:350
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:454
msgid "Continue"
msgstr "داۋاملاشتۇر"

#: ../gtk/apport-gtk.py:224 ../debian/tmp/usr/share/apport/apport-gtk.py:224
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:276
msgid "Force Closed"
msgstr "مەجبۇرىي يېپىلغان"

#: ../gtk/apport-gtk.py:225 ../gtk/apport-gtk.py:284
#: ../debian/tmp/usr/share/apport/apport-kde.py:214
#: ../debian/tmp/usr/share/apport/apport-kde.py:357
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:222
#: ../kde/apport-kde.py:214 ../kde/apport-kde.py:357
#: ../debian/tmp/usr/share/apport/apport-gtk.py:225
#: ../debian/tmp/usr/share/apport/apport-gtk.py:284
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:232
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:273
msgid "Relaunch"
msgstr "قايتا ئىجرا قىل"

#: ../gtk/apport-gtk.py:234 ../debian/tmp/usr/share/apport/apport-gtk.py:234
#, python-format
msgid "The application %s has stopped responding."
msgstr "پروگرامما %s جاۋاب قايتۇرۇشتىن توختىدى."

#: ../gtk/apport-gtk.py:238 ../debian/tmp/usr/share/apport/apport-gtk.py:238
#, python-format
msgid "The program \"%s\" has stopped responding."
msgstr "پروگرامما «%s» جاۋاب قايتۇرۇشتىن توختىدى."

#: ../gtk/apport-gtk.py:253 ../debian/tmp/usr/share/apport/apport-kde.py:184
#: ../kde/apport-kde.py:184 ../debian/tmp/usr/share/apport/apport-gtk.py:253
#, python-format
msgid "Package: %s"
msgstr "بوغچا: %s"

#: ../gtk/apport-gtk.py:260 ../debian/tmp/usr/share/apport/apport-kde.py:190
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:132
#: ../kde/apport-kde.py:190 ../debian/tmp/usr/share/apport/apport-gtk.py:260
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:137
msgid "Sorry, a problem occurred while installing software."
msgstr "كەچۈرۈڭ، يۇمشاق دېتال ئورناتقاندا بىر خاتالىق كۆرۈلدى."

#: ../gtk/apport-gtk.py:269 ../gtk/apport-gtk.py:288
#: ../debian/tmp/usr/share/apport/apport-kde.py:197 ../kde/apport-kde.py:197
#: ../debian/tmp/usr/share/apport/apport-gtk.py:269
#: ../debian/tmp/usr/share/apport/apport-gtk.py:288
#, python-format
msgid "The application %s has experienced an internal error."
msgstr "پروگرامما %s نىڭدا بىر ئىچكى خاتالىق يۈز بەردى."

#: ../gtk/apport-gtk.py:272 ../debian/tmp/usr/share/apport/apport-kde.py:201
#: ../kde/apport-kde.py:201 ../debian/tmp/usr/share/apport/apport-gtk.py:272
#, python-format
msgid "The application %s has closed unexpectedly."
msgstr "بۇ %s ئەپ تاسادىپىي تاقالدى."

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:9 ../gtk/apport-gtk.py:283
#: ../debian/tmp/usr/share/apport/apport-kde.py:213 ../gtk/apport-gtk.ui.h:9
#: ../kde/apport-kde.py:213 ../debian/tmp/usr/share/apport/apport-gtk.py:283
msgid "Leave Closed"
msgstr "تاقاق پېتى قالدۇر"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:4 ../gtk/apport-gtk.py:296
#: ../debian/tmp/usr/share/apport/apport-kde.py:220 ../gtk/apport-gtk.ui.h:4
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_kde.py:252
#: ../kde/apport-kde.py:220 ../debian/tmp/usr/share/apport/apport-gtk.py:296
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:302
#: ../debian/tmp/usr/share/apport/testsuite/test_ui_gtk.py:342
msgid "If you notice further problems, try restarting the computer."
msgstr ""
"ئەگەر تېخىمۇ كۆپ مەسىلىنى بايقىسىڭىز، كومپيۇتېرنى قايتا قوزغىتىشنى سىناڭ."

#: ../gtk/apport-gtk.py:300 ../debian/tmp/usr/share/apport/apport-kde.py:224
#: ../kde/apport-kde.py:224 ../debian/tmp/usr/share/apport/apport-gtk.py:300
msgid "Ignore future problems of this type"
msgstr "بۇ تۈردىكى كەلگۈسىدىكى مەسىلىگە سەل قاراش"

#: ../gtk/apport-gtk.py:573 ../debian/tmp/usr/share/apport/apport-kde.py:268
#: ../kde/apport-kde.py:268 ../debian/tmp/usr/share/apport/apport-gtk.py:573
msgid "Hide Details"
msgstr "تەپسىلاتلارنى يوشۇر"

#: ../debian/tmp/usr/share/apport/apport-kde.py:294 ../kde/apport-kde.py:294
msgid "Username:"
msgstr "ئىشلەتكۈچى ئاتى:"

#: ../debian/tmp/usr/share/apport/apport-kde.py:295 ../kde/apport-kde.py:295
msgid "Password:"
msgstr "ئىم:"

#: ../debian/tmp/usr/share/apport/apport-kde.py:382 ../kde/apport-kde.py:382
msgid "Collecting Problem Information"
msgstr "چاتاق ھەققىدىكى ئۇچۇرلارنى توپلاۋاتىدۇ"

#: ../debian/tmp/usr/share/apport/apport-kde.py:384 ../kde/apport-kde.py:384
msgid ""
"The collected information can be sent to the developers to improve the "
"application. This might take a few minutes."
msgstr ""
"ئىجادىيەتچىنىڭ پروگرامما ئىقتىدارىنى ياخشىلىشىغا قۇلايلىق يارىتىش ئۈچۈن، "
"توپلانغان ئۇچۇرلار ئىجادىيەتچىگە يوللىنىدۇ. بۇنىڭغا بىرقانچە مىنۇت كېتىدۇ."

#: ../debian/tmp/usr/share/apport/apport-kde.py:410 ../kde/apport-kde.py:410
msgid "Uploading Problem Information"
msgstr "چاتاق ھەققىدىكى ئۇچۇرلارنى يۈكلەۋاتىدۇ"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:15
#: ../debian/tmp/usr/share/apport/apport-kde.py:412 ../gtk/apport-gtk.ui.h:15
#: ../kde/apport-kde.py:412
msgid ""
"The collected information is being sent to the bug tracking system. This "
"might take a few minutes."
msgstr ""
"توپلانغان ئۇچۇرلارنى كەمتۈك باشقۇرۇش سىستېمىسىغا ئەۋەتمەكچى. بۇنىڭغا ئازراق "
"ۋاقىت كېتىدۇ."

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:1
#: ../debian/tmp/usr/share/apport/apport-kde.py:446
#: ../debian/tmp/usr/share/apport/apport-kde.py:482 ../gtk/apport-gtk.ui.h:1
#: ../kde/apport-kde.py:446 ../kde/apport-kde.py:482
msgid "Apport"
msgstr "Apport"

#: ../apport/com.ubuntu.apport.policy.in.h:1
msgid "Collect system information"
msgstr "سىستېما ئۇچۇرلىرىنى توپلا"

#: ../apport/com.ubuntu.apport.policy.in.h:2
msgid ""
"Authentication is required to collect system information for this problem "
"report"
msgstr ""
"بۇ مەسىلىنى مەلۇم قىلىشتا سىستېما ئۇچۇرلىرىنى توپلاش كېرەك، بىراق بۇنىڭ "
"ئۈچۈن كىملىك دەلىللەش زۆرۈردۇر."

#: ../apport/com.ubuntu.apport.policy.in.h:3
msgid "System problem reports"
msgstr ""

#: ../apport/com.ubuntu.apport.policy.in.h:4
msgid ""
"Please enter your password to access problem reports of system programs"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:2 ../gtk/apport-gtk.ui.h:2
msgid "Crash report"
msgstr "يىمىرىلىش دوكلاتى"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:3 ../gtk/apport-gtk.ui.h:3
msgid "<big><b>Sorry, an internal error happened.</b></big>"
msgstr "<big><b>كەچۈرۈڭ، ئىچكى خاتالىق يۈز بەردى.</b></big>"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:5 ../gtk/apport-gtk.ui.h:5
msgid "Send an error report to help fix this problem"
msgstr ""
"بۇ مەسىلىنى ئوڭلاشقا ياردەم قىلىش ئۈچۈن خاتالىق دوكلاتىدىن بىرنى يوللاڭ"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:6 ../gtk/apport-gtk.ui.h:6
msgid "Ignore future problems of this program version"
msgstr "بۇ پروگرامما نەشرىنىڭ كەلگۈسىدىكى مەسىلىلىرىگە پەرۋا قىلما"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:8 ../gtk/apport-gtk.ui.h:8
msgid "_Examine locally"
msgstr "يەرلىكتە تەكشۈر(_E)"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:11 ../gtk/apport-gtk.ui.h:11
msgid "<big><b>Collecting problem information</b></big>"
msgstr "<big><b>مەسىلە ھەققىدە ئۇچۇرلارنى توپلاۋاتىدۇ</b></big>"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:12 ../gtk/apport-gtk.ui.h:12
msgid ""
"Information is being collected that may help the developers fix the problem "
"you report."
msgstr ""
"سىز مەلۇم قىلغان مەسىلىنى ئىجادىيەتچىلەرنىڭ تۈزىتىشىگە ياردىمى بولسۇن دەپ "
"ئۇچۇرلار توپلاندى."

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:14 ../gtk/apport-gtk.ui.h:14
msgid "<big><b>Uploading problem information</b></big>"
msgstr "<big><b>مەسىلە ھەققىدىكى ئۇچۇرلارنى يۈكلەۋاتىدۇ</b></big>"

#: ../kde/apport-kde-mimelnk.desktop.in.h:1
msgid "Apport crash file"
msgstr "Apport چاتاق ھۆججىتى"

#: ../debian/tmp/usr/bin/apport-unpack.py:22 ../bin/apport-unpack.py:22
#, python-format
msgid "Usage: %s <report> <target directory>"
msgstr "ئىشلىتىش ئۇسۇلى: %s <مەلۇمات> <نىشان مۇندەرىجە>"

#: ../debian/tmp/usr/bin/apport-unpack.py:46 ../bin/apport-unpack.py:46
msgid "Destination directory exists and is not empty."
msgstr "نىشان مۇندەرىجە بار ھەم بوش ئەمەس."

#, python-format
#~ msgid "Sorry, the program \"%s\" closed unexpectedly."
#~ msgstr "كەچۈرۈڭ، پروگرامما «%s» ئويلىمىغان يەردىن تاقىلىپ قالدى."

#, python-format
#~ msgid "Sorry, the package \"%s\" failed to install or upgrade."
#~ msgstr "كەچۈرۈڭ، بوغچا «%s» نى ئورنىتىش ياكى يۈكسەلدۈرۈش مەغلۇپ بولدى."

#~ msgid "Your system encountered a serious kernel problem."
#~ msgstr "سىستېمىڭىزنىڭ يادروسىدا(kernel) ئېغىر مەسىلە يۈز بەردى."

#~ msgid "Kernel problem"
#~ msgstr "يادرو(kernel) دىكى مەسىلە"

#~ msgid "Send this data to the developers?"
#~ msgstr "بۇ سانلىق-مەلۇماتلارنى ئىجادىيەتچىگە ئەۋەتسۇنمۇ؟"

#, no-c-format
#~ msgid ""
#~ "<span weight=\"bold\" size=\"larger\">Sorry, the package \"%s\" failed to "
#~ "install or upgrade.</span>"
#~ msgstr ""
#~ "<span weight=\"bold\" size=\"larger\">كەچۈرۈڭ، بوغچا «%s» نى ئورنىتىش ياكى "
#~ "يۈكسەلدۈرۈش مەغلۇپ بولدى.</span>"

#~ msgid "Package problem"
#~ msgstr "بوغچىدىكى مەسىلە"

#, python-format
#~ msgid "This is not a genuine %s package"
#~ msgstr "بۇ رەسمىي  %s بوغچىسى ئەمەس"

#, python-format
#~ msgid "The package \"%s\" failed to install or upgrade."
#~ msgstr "بوغچا «%s» نى ئورنىتىش ياكى يېڭىلاش مەغلۇپ بولدى."

#, python-format
#~ msgid "Sorry, the application %s has closed unexpectedly."
#~ msgstr "كەچۈرۈڭ بۇ %s ئەپ تاسادىپىي تاقالدى."
